UG Documentation for Form Field Undo Redo support, Bookmark expand and collapse, Signature Field.
syncfusion-content/wpf-docs pull request #1186
Opened 2024-02-28 08:27 UTC by HemalathaDuraisamy

UG Documentation for Form Field Undo Redo support, Bookmark expand and collapse, Signature Field.

2024-02-28 08:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/console)**

2024-02-28 08:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/console)**

2024-02-28 08:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/WPF-docs/60/)<br/>**

2024-02-28 13:19 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/62/console)**

2024-02-28 13:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/62/console)**

2024-02-28 13:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/WPF-docs/62/)<br/>**

2024-03-04 04:24 UTC, RajaVigneshB approved these changes
Approving the changes

2024-03-07 08:05 UTC, Vikassekar requested changes
Can you address these feedbacks?

2024-03-07 08:05 UTC, Vikassekar commented on wpf/Pdf-Viewer/Bookmark-Navigation.md
> +## Displaying bookmark
Instead of mentioning "Displaying bookmark" can you mention as "Expand bookmark panel Programmatically".

2024-03-07 08:05 UTC, Vikassekar commented on wpf/Pdf-Viewer/Bookmark-Navigation.md
> +The bookmark are displayed by clicking the bookmark icon in the left pane.To display bookmark pane from code behind, use the following code example.
use panel instead of pane

2024-03-07 08:05 UTC, Vikassekar commented on wpf/Pdf-Viewer/Bookmark-Navigation.md
> +## Displaying bookmark
add this topic below "[Enabling and disabling bookmark feature](https://help.syncfusion.com/wpf/pdf-viewer/bookmark-navigation#enabling-and-disabling-bookmark-feature)"

2024-03-07 08:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/5/console)**

2024-03-08 05:22 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/console)**

2024-03-08 05:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/console)**

2024-03-08 05:29 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/artifact/cireports/)<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/8/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-08 05:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/9/console)**

2024-03-08 05:33 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/9/artifact/cireports/)<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/9/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/9/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/9/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/9/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/9/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/9/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/9/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/9/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/9/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-08 06:01 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/10/console)**

2024-03-08 07:24 UTC, RajaVigneshB requested changes

2024-03-08 07:24 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/Form-Filling-in-PDF.md
> +The PDF viewer allows to add and delete for the signature in the signature form field.
Please add detail notes on this

2024-03-08 07:24 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/Form-Filling-in-PDF.md
> +![WPF PDF Viewer Delete a Signature from Signature field](form-filling-images\wpf-pdf-viewer-signature-form-field-delete.png)
As we discussed, change the images

2024-03-08 07:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/11/console)**

2024-03-08 07:59 UTC, HemalathaDuraisamy commented on wpf/Pdf-Viewer/Form-Filling-in-PDF.md
> +![WPF PDF Viewer Delete a Signature from Signature field](form-filling-images\wpf-pdf-viewer-signature-form-field-delete.png)
Changed the images

2024-03-08 07:59 UTC, HemalathaDuraisamy commented on wpf/Pdf-Viewer/Form-Filling-in-PDF.md
> +The PDF viewer allows to add and delete for the signature in the signature form field.
Modified the content detaily

2024-03-08 08:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/11/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/11/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/11/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/11/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/11/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/11/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/11/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/11/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/11/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-08 08:32 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/12/console)**

2024-03-08 08:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [PdfViewerWPFUG](https://ci.syncfusion.com/job/Content/job/wpf-docs/12/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/12/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/12/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/12/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/12/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/12/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/12/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/12/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/12/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-08 09:00 UTC, HemalathaDuraisamy commented
This is the duplicate UG pr, hence closing the Pr.

2024-03-08 09:00 UTC, closed without merging