871182  Apply themes support code snippet for PdfViewer Control
syncfusion-content/wpf-docs pull request #1196
Opened 2024-03-05 08:50 UTC by HemalathaDuraisamy

871182  Apply themes support code snippet for PdfViewer Control

2024-03-05 08:51 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WPFPdfviewerTheme](https://ci.syncfusion.com/job/Content/job/wpf-docs/1/console)**

2024-03-05 08:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPFPdfviewerTheme](https://ci.syncfusion.com/job/Content/job/wpf-docs/1/console)**

2024-03-05 09:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPFPdfviewerTheme](https://ci.syncfusion.com/job/Content/job/wpf-docs/1/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/1/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/1/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/1/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/1/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/1/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/1/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/1/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/1/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 07:05 UTC, RajaVigneshB requested changes

2024-03-13 07:05 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/Getting-Started.md
> +    HomeGrid.Children.Add(pdfViewer);
Add this line below the PdfViewer initialization

2024-03-13 07:05 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/Getting-Started.md
> +
Remove unwanted spaces

2024-03-13 07:05 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/Getting-Started.md
> +    Public Sub New()
Remove unwanted spaces.

2024-03-13 07:57 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WPFPdfviewerTheme](https://ci.syncfusion.com/job/Content/job/wpf-docs/31/console)**

2024-03-13 08:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPFPdfviewerTheme](https://ci.syncfusion.com/job/Content/job/wpf-docs/31/console)**

2024-03-13 08:03 UTC, HemalathaDuraisamy commented on wpf/Pdf-Viewer/Getting-Started.md
> +    HomeGrid.Children.Add(pdfViewer);
Modified the line of the code

2024-03-13 08:03 UTC, HemalathaDuraisamy commented on wpf/Pdf-Viewer/Getting-Started.md
> +
Removed the unwanted space

2024-03-13 08:03 UTC, HemalathaDuraisamy commented on wpf/Pdf-Viewer/Getting-Started.md
> +    Public Sub New()
Removed the unwanted space

2024-03-13 08:04 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPFPdfviewerTheme](https://ci.syncfusion.com/job/Content/job/wpf-docs/31/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/31/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/31/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/31/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/31/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/31/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/31/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/31/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/31/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 08:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPFPdfviewerTheme](https://ci.syncfusion.com/job/Content/job/wpf-docs/32/console)**

2024-03-13 08:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPFPdfviewerTheme](https://ci.syncfusion.com/job/Content/job/wpf-docs/32/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/32/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/32/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/32/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/32/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/32/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/32/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/32/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/32/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 10:08 UTC, RajaVigneshB approved these changes

2024-03-13 10:09 UTC, merged