UG documentation for Serialization in WPF Image Editor
syncfusion-content/wpf-docs pull request #1203
Opened 2024-03-08 11:09 UTC by Shalini-Ashokan

### Description
UG documentation for Serialization in WPF Image Editor

2024-03-08 11:14 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/14/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/14/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/14/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/14/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/14/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/14/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/14/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/14/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/14/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-11 08:41 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/17/console)**

2024-03-11 08:47 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/17/console)**

2024-03-11 09:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/17/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/17/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/17/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/17/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/17/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/17/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/17/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/17/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/17/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-11 09:33 UTC, karthikraja-arumugam commented on wpf/Image-Editor/serialization.md
> +title: Serialization in syncfusion SfImageEditor WPF.
This section describes how to serialize and deserialize the annotations in SfImageEditor control for the WPF platform.

2024-03-11 09:36 UTC, karthikraja-arumugam commented on wpf/Image-Editor/serialization.md
> +# Serialization in SfImageEditor
# Serialization in Image Editor (SfImageEditor)

2024-03-11 09:37 UTC, karthikraja-arumugam commented on wpf/Image-Editor/serialization.md
> +The Image Editor control provides support for serializing and deserializing annotations, freehand drawing, text, and toolbar settings. You can save the current state of the image editor and load it b
The Image Editor control provides support to serialize and deserialize the shape, text, pen annotations, and custom view along with their settings. You can save the current state of the image editor annotations and load it back when it is needed.

2024-03-11 09:38 UTC, karthikraja-arumugam commented on wpf/Image-Editor/serialization.md
> +The `Serialize()` method is used to serialize the current edits of shapes. It allows you to store the `SfImageEditor` annotation settings using the `Serialize` method by passing the stream as a param
The Serialize method is used to serialize the current edits of annotations. It allows you to store the SfImageEditor annotations to the stream by passing the stream as a parameter to the Serialize method.

2024-03-11 09:39 UTC, karthikraja-arumugam commented on wpf/Image-Editor/serialization.md
> +	//To Save as stream in file
remove comment

2024-03-11 09:39 UTC, karthikraja-arumugam commented on wpf/Image-Editor/serialization.md
> +The `Deserialize()` method is used to deserialize the edits made on an image. It allows you to reload the `SfImageEditor` control with the settings available in the stream.
The Deserialize method is used to deserialize the annotations over an image. It allows you to reload the SfImageEditor control with the annotations available in the stream.

2024-03-11 09:42 UTC, karthikraja-arumugam commented on wpf/Image-Editor/serialization.md
> +{% endhighlight %}
add topic

Annotations collection

Mention about read only collection

2024-03-11 10:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/18/console)**

2024-03-11 10:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/18/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/18/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/18/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/18/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/18/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/18/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/18/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/18/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/18/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-11 11:14 UTC, Shalini-Ashokan commented on wpf/Image-Editor/serialization.md
> +{% endhighlight %}
Added topic and mentioned read only collection

2024-03-11 11:14 UTC, Shalini-Ashokan commented on wpf/Image-Editor/serialization.md
> +The `Deserialize()` method is used to deserialize the edits made on an image. It allows you to reload the `SfImageEditor` control with the settings available in the stream.
Updated

2024-03-11 11:14 UTC, Shalini-Ashokan commented on wpf/Image-Editor/serialization.md
> +	//To Save as stream in file
removed

2024-03-11 11:14 UTC, Shalini-Ashokan commented on wpf/Image-Editor/serialization.md
> +The `Serialize()` method is used to serialize the current edits of shapes. It allows you to store the `SfImageEditor` annotation settings using the `Serialize` method by passing the stream as a param
Updated

2024-03-11 11:14 UTC, Shalini-Ashokan commented on wpf/Image-Editor/serialization.md
> +The Image Editor control provides support for serializing and deserializing annotations, freehand drawing, text, and toolbar settings. You can save the current state of the image editor and load it b
Updated

2024-03-11 11:15 UTC, Shalini-Ashokan commented on wpf/Image-Editor/serialization.md
> +title: Serialization in syncfusion SfImageEditor WPF.
Updated

2024-03-12 13:08 UTC, karthikraja-arumugam commented on wpf/Image-Editor/serialization.md
> +    dialog.Title = "Save XAML";
Save XML

2024-03-12 13:08 UTC, karthikraja-arumugam commented on wpf/Image-Editor/serialization.md
> +    dialog.Filter = "XAML File (*.xaml)|*.xaml";
dialog.Filter = "XAML File (*.xaml)|*.xaml";

use xml file

2024-03-12 13:08 UTC, karthikraja-arumugam commented on wpf/Image-Editor/serialization.md
> +            imageEditor.Reset();
remove reset

2024-03-12 13:10 UTC, karthikraja-arumugam commented on wpf/Image-Editor/serialization.md
> +The Image Editor provides the read-only collection of annotations using the `Annotations` property.
The Image Editor provides the read-only collection of annotations using the `Annotations` property. The Annotations property contains all the annotations currently visible in image editor.

Note: This collection will be reset if the background image has been changed.

2024-03-12 13:16 UTC, Shalini-Ashokan commented on wpf/Image-Editor/serialization.md
> +    dialog.Filter = "XAML File (*.xaml)|*.xaml";
used xml file

2024-03-12 13:16 UTC, Shalini-Ashokan commented on wpf/Image-Editor/serialization.md
> +            imageEditor.Reset();
removed

2024-03-12 13:16 UTC, Shalini-Ashokan commented on wpf/Image-Editor/serialization.md
> +The Image Editor provides the read-only collection of annotations using the `Annotations` property.
Updated

2024-03-12 13:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/23/console)**

2024-03-12 13:25 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/23/artifact/cireports/)<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/23/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/23/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/23/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/23/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/23/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/23/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/23/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/23/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/23/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 05:46 UTC, florenceliliana requested changes
The content review is completed.

2024-03-13 05:46 UTC, florenceliliana commented on wpf/Image-Editor/serialization.md
> +title: Serialization in syncfusion SfImageEditor WPF.
title: Serialization in Syncfusion SfImageEditor WPF

2024-03-13 06:08 UTC, Shalini-Ashokan commented on wpf/Image-Editor/serialization.md
> +title: Serialization in syncfusion SfImageEditor WPF.
Updated

2024-03-13 06:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/30/console)**

2024-03-13 06:10 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/30/artifact/cireports/)<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/30/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/30/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/30/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/30/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/30/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/30/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/30/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/30/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/30/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 09:31 UTC, florenceliliana reviewed
The content review is completed.

2024-03-13 09:31 UTC, florenceliliana commented on wpf/Image-Editor/serialization.md
> +The following code snippet only adds a rectangle shape from the `Annotations` collection.
The following code sample only adds a rectangle shape from the `Annotations` collection.

2024-03-13 10:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/34/console)**

2024-03-13 10:07 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/34/artifact/cireports/)<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/34/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/34/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/34/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/34/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/34/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/34/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/34/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/34/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/34/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-13 10:09 UTC, Shalini-Ashokan commented on wpf/Image-Editor/serialization.md
> +The following code snippet only adds a rectangle shape from the `Annotations` collection.
Updated

2024-03-13 10:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/35/console)**

2024-03-13 10:19 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/35/artifact/cireports/)<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/35/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/35/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/35/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/35/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/35/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/35/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/35/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/35/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/35/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 05:50 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/console)**

2024-03-14 06:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/console)**

2024-03-14 06:07 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/artifact/cireports/)<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/41/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 10:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/46/console)**

2024-03-14 10:32 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/wpf-docs/46/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-14 10:33 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: FAILURE :x:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/46/)<br/>**

2024-03-14 10:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/47/console)**

2024-03-14 10:35 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ImageEditor_Serialization](https://ci.syncfusion.com/job/Content/job/wpf-docs/47/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/47/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/47/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/47/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/47/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/47/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/47/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/47/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/47/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 10:45 UTC, karthikraja-arumugam approved these changes
This is fine

2024-03-14 10:47 UTC, MuniappanSubramanian approved these changes

2024-03-14 10:49 UTC, Nijamudeen-Mohamed approved these changes

2024-03-14 10:49 UTC, merged