ES-875077 - Prepared the user guide documentation for automation using Appium in WPF
syncfusion-content/wpf-docs pull request #1213
Opened 2024-03-14 11:02 UTC by vijayarasan

**Description**

UG documentation for automation using Appium in WPF.

**Work Item Link:** https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/875077

2024-03-14 12:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-875077_Appium](https://ci.syncfusion.com/job/Content/job/wpf-docs/54/console)**

2024-03-14 12:52 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/54/artifact/cireports/)<br/>Build Location: [ES-875077_Appium](https://ci.syncfusion.com/job/Content/job/wpf-docs/54/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/54/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/54/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/54/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/54/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/54/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/54/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/54/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/54/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 12:59 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/55/artifact/cireports/)<br/>Build Location: [ES-875077_Appium](https://ci.syncfusion.com/job/Content/job/wpf-docs/55/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/55/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/55/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/55/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/55/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/55/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/55/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/55/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/55/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 13:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-875077_Appium](https://ci.syncfusion.com/job/Content/job/wpf-docs/57/console)**

2024-03-15 12:31 UTC, florenceliliana requested changes
The content review is completed.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +N> During our internal testing, it was noted that the auto-generated code might not successfully identify the user interface element using its complete path.
N> During our internal testing, it was noted that the auto-generated code might need to identify the user interface element using its complete path successfully.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +N> Ensure that all element paths are complete and begin with "/Window" to prevent this.
N> Ensure all element paths are complete and begin with "/Window" to prevent this.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +After completing the implementation of TestMethod, you can test the application by following these steps.
After completing the implementation of TestMethod, test the application using the following steps.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +**Step 2:** Now, the test will launch your application, repeat all recorded steps, and close the application afterwards. All test details can be found in the Test Explorer.
**Step 2:** Now, the test will launch your application, repeat all recorded steps, and close the application. All test details can be found in the Test Explorer.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +        // Create the WindowsDriver session
// Create the WindowsDriver session.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +// Use the UI Recorder Tool
// Use the UI Recorder Tool.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +Appium is an open-source tool that allows you to create automated UI tests for applications. This section will guide you on how to automate your WPF application by utilizing Appium along with [Window
Appium is an open-source tool that allows you to create automated UI tests for applications. This section will guide you on how to automate your WPF application by utilizing Appium along with [Windows Application Driver] (https://github.com/Microsoft/WinAppDriver) and the UI Recorder tool.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +N> To obtain the UI Recorder app, by visit the Windows Application Driver [releases](https://github.com/Microsoft/WinAppDriver/releases) page and scroll down.
N> To obtain the UI Recorder app, visit the Windows Application Driver [releases](https://github.com/Microsoft/WinAppDriver/releases) page and scroll down.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +Run WinAppDriver.exe as an administrator and observe the command prompt displaying information about the URL and port that the service is listening on. The default URL is http://127.0.0.1:4723. The c
Run WinAppDriver.exe as an administrator and observe the command prompt displaying information about the URL and port that the service is listening to. The default URL is http://127.0.0.1:4723. The command prompt also functions as a logger, showing HTTP requests and JSON payloads whenever the Appium SDK performs an interaction.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +N> This process should be run continuously until the test is complete. This serves as the listener server during testing on the machine.
N> This process should be run continuously until the test is complete. This serves as the listener server during machine testing.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +    // Path to your WPF application executable
// Path to your WPF application executable.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +    // Manually implement the test
// Manually implement the test.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +            // Create the WindowsDriver session
// Create the WindowsDriver session.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +        // Create the WindowsDriver session
// Create the WindowsDriver session.

2024-03-15 12:31 UTC, florenceliliana commented on wpf/Testing/appium.md
> +**Step 2:** Run the application (e.g. EmployeeFormDemo)
**Step 2:** Run the application (e.g. EmployeeFormDemo).

2024-03-18 07:58 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-875077_Appium](https://ci.syncfusion.com/job/Content/job/wpf-docs/74/console)**

2024-03-18 08:00 UTC, vijayarasan commented on wpf/Testing/appium.md
> +Appium is an open-source tool that allows you to create automated UI tests for applications. This section will guide you on how to automate your WPF application by utilizing Appium along with [Window
When adding space between a link, it will not be recognized as a link in the UG documentation. Therefore, this case should be ignored.

2024-03-18 08:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-875077_Appium](https://ci.syncfusion.com/job/Content/job/wpf-docs/74/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/74/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/74/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/74/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/74/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/74/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/74/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/74/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/74/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-18 08:02 UTC, vijayarasan commented on wpf/Testing/appium.md
> +N> During our internal testing, it was noted that the auto-generated code might not successfully identify the user interface element using its complete path.
Reviewed content does not explain the same meaning as the content. Therefore, this case will be ignored.

2024-05-02 11:36 UTC, vijayarasan commented
The hotfix PR has been merged and the content has been published in the user guide. Therefore, I am closing this PR.

2024-05-02 11:36 UTC, closed without merging