WPF-876347-Updated the UG documentation for the newly implemented features
syncfusion-content/wpf-docs pull request #1215
Opened 2024-03-14 21:06 UTC by Karthick-Arjunan

2024-03-14 21:07 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/58/console)**

2024-03-14 21:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/58/console)**

2024-03-14 21:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/58/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/58/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/58/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/58/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/58/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/58/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/58/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/58/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/58/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-14 21:45 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/59/console)**

2024-03-14 22:02 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/59/console)**

2024-03-14 22:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/59/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/59/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/59/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/59/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/59/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/59/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/59/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/59/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/59/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 04:44 UTC, durga-muthu requested changes

2024-03-15 04:44 UTC, durga-muthu commented on wpf/Docking/MDI-TDI-functionalities.md
> +    tab.IsNewButtonEnabled = true;
Already style has been provided. then why we are setting the properties in loaded?

2024-03-15 04:44 UTC, durga-muthu commented on wpf/Docking/MDI-TDI-functionalities.md
> +EventManager.RegisterClassHandler(typeof(DocumentTabControl), LoadedEvent, new RoutedEventHandler(DocumentTabControl_Loaded), true);
remove this code.

2024-03-15 04:44 UTC, durga-muthu commented on wpf/Docking/MDI-TDI-functionalities.md
> +The NewButtonClick event is used to notifies when the new button(+) is clicked in DockingManager. In TDI document, new tab can be added at runtime by utilizing this event.
TDI is for tabbed document interface, please use correct sentence here.

2024-03-15 04:57 UTC, Karthick-Arjunan commented on wpf/Docking/MDI-TDI-functionalities.md
> +    tab.IsNewButtonEnabled = true;
I have provided code snippet for adding the new button through the code behind.

2024-03-15 04:57 UTC, Karthick-Arjunan commented on wpf/Docking/MDI-TDI-functionalities.md
> +EventManager.RegisterClassHandler(typeof(DocumentTabControl), LoadedEvent, new RoutedEventHandler(DocumentTabControl_Loaded), true);
removed.

2024-03-15 04:57 UTC, Karthick-Arjunan commented on wpf/Docking/MDI-TDI-functionalities.md
> +The NewButtonClick event is used to notifies when the new button(+) is clicked in DockingManager. In TDI document, new tab can be added at runtime by utilizing this event.
Changed the content.

2024-03-15 04:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/console)**

2024-03-15 05:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/60/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 05:34 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/wpf-docs/61/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-15 05:35 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/61/)<br/>**

2024-03-15 05:35 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/wpf-docs/62/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-03-15 05:35 UTC, durga-muthu approved these changes

2024-03-15 05:36 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/63/console)**

2024-03-15 05:38 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/63/console)**

2024-03-15 05:51 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-869120](https://ci.syncfusion.com/job/Content/job/wpf-docs/63/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/63/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/63/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/63/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/63/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/63/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/63/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/63/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/63/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-03-15 06:24 UTC, merged