SEO-181938-WPF-int-changes
syncfusion-content/wpf-docs pull request #1257
Opened 2024-04-04 14:20 UTC by Sharly-Atieno

Hi @MallikaRK ,

Worked on wpf changes.

Regards,
Sharly A.

2024-04-04 14:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/108/console)**

2024-04-04 14:22 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/108/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/108/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/108/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/108/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/108/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/108/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/108/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/108/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/108/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-12 09:57 UTC, MallikaRK requested changes
commented

2024-04-12 09:57 UTC, MallikaRK commented on wpf/DataPager/Overview.md
>  The SfDataPager control provides a configurable user interface for paging using a data collection. You can bind the SfDataPager to any IEnumerable <a>(http://msdn.microsoft.com/en-us/library/system.c
Can you recheck the URL?
<img width="761" alt="image" src="https://github.com/syncfusion-content/wpf-docs/assets/44014283/5c0f6efa-9966-4f4d-a47f-a808814f649b">

2024-04-12 11:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/console)**

2024-04-12 11:10 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/artifact/cireports/)<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/113/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-12 11:14 UTC, Sharly-Atieno commented on wpf/DataPager/Overview.md
>  The SfDataPager control provides a configurable user interface for paging using a data collection. You can bind the SfDataPager to any IEnumerable <a>(http://msdn.microsoft.com/en-us/library/system.c
resolved

2024-04-12 11:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/console)**

2024-04-12 11:19 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/artifact/cireports/)<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/114/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-12 11:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/console)**

2024-04-12 11:25 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/artifact/cireports/)<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/)<br/>Technical Error(s): 0<br/>Spelling Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/artifact/cireports/spellcheck/spellcheckreport.htm)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/116/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-12 11:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/117/console)**

2024-04-12 11:34 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/wpf-docs/117/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-04-12 11:34 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: FAILURE :x:<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/117/)<br/>**

2024-04-12 11:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/118/console)**

2024-04-12 11:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-181938-WPF-int-changes](https://ci.syncfusion.com/job/Content/job/wpf-docs/118/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/118/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/118/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/118/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/118/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/118/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/118/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/118/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/118/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-04-12 11:52 UTC, MallikaRK approved these changes
approved

2024-04-15 09:35 UTC, Aishwarya-Ganesan approved these changes

2024-04-15 09:35 UTC, merged