883480 Include Silent printing with printer name
syncfusion-content/wpf-docs pull request #1296
Opened 2024-05-17 13:06 UTC by KrithikaGanesan

Include Silent printing with printer name

2024-05-17 13:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [883480](https://ci.syncfusion.com/job/Content/job/wpf-docs/161/console)**

2024-05-17 13:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [883480](https://ci.syncfusion.com/job/Content/job/wpf-docs/161/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/161/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/161/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/161/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/161/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/161/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/161/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/161/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/161/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-06-28 08:32 UTC, Vikassekar requested changes

2024-06-28 08:32 UTC, Vikassekar commented on wpf/Pdf-Viewer/Printing-PDF-Files.md
> +pdfviewer1.Print("Microsoft Print to PDF");
instead of mentioning the microsoft print to pdf, define the variable and set to the method

string printerName = "enter the printer name";
pdfviewer1.Print(printerName );

2024-06-28 14:25 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Printing-PDF-Files.md
> +pdfviewer1.Print("Microsoft Print to PDF");
I have done the changes

2024-06-28 14:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [883480](https://ci.syncfusion.com/job/Content/job/wpf-docs/438/console)**

2024-06-28 14:27 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/wpf-docs/438/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-06-28 14:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [883480](https://ci.syncfusion.com/job/Content/job/wpf-docs/439/console)**

2024-06-28 14:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [883480](https://ci.syncfusion.com/job/Content/job/wpf-docs/439/console)**

2024-06-28 14:46 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [883480](https://ci.syncfusion.com/job/Content/job/wpf-docs/439/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/439/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/439/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/439/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/439/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/439/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/439/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/439/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/439/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-06-28 15:17 UTC, Vikassekar approved these changes

2024-06-28 15:17 UTC, merged