897889- Removed the VS 2008,2010,2012, and 2013 for the WPF platform.
syncfusion-content/wpf-docs pull request #1437
Opened 2024-07-17 10:42 UTC by YuvarajMasilamani

Hi @SubashiniMahendran 

I have removed the VS 2008,2010,2012, and 2013 for the WPF platform. Please review and merge the changes.

Regards 
Yuvaraj M

2024-07-17 10:43 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Removing_VS_2012_and_2013](https://ci.syncfusion.com/job/Content/job/wpf-docs/451/console)**

2024-07-17 10:45 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/451/artifact/cireports/)<br/>Build Location: [Removing_VS_2012_and_2013](https://ci.syncfusion.com/job/Content/job/wpf-docs/451/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/451/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/451/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/451/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/451/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/451/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/451/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/451/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/451/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-07-17 10:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Removing_VS_2012_and_2013](https://ci.syncfusion.com/job/Content/job/wpf-docs/452/console)**

2024-07-17 10:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Removing_VS_2012_and_2013](https://ci.syncfusion.com/job/Content/job/wpf-docs/452/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/452/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/452/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/452/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/452/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/452/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/452/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/452/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/452/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-07-17 11:25 UTC, SubashiniMahendran requested changes

2024-07-17 11:25 UTC, SubashiniMahendran commented on wpf/Charts/CodedUI.md
> -
check and include VS2015

2024-07-17 11:25 UTC, SubashiniMahendran commented on wpf/DataGrid/UI-Automation.md
> -
check and include VS2015

2024-07-17 11:25 UTC, SubashiniMahendran commented on wpf/Grouping/Overview.md
>  <tr>
remove VS2005

2024-07-17 11:25 UTC, SubashiniMahendran commented on wpf/Sparkline/Getting-started.md
>  * Add the following namespace in your XAML page:
check with concern team

2024-07-17 11:25 UTC, SubashiniMahendran commented on wpf/Range-Selector/Getting-Started.md
> -
check with concern team as discussed

2024-07-17 11:58 UTC, YuvarajMasilamani commented on wpf/Grouping/Overview.md
>  <tr>
removed

2024-07-17 12:02 UTC, YuvarajMasilamani commented on wpf/Charts/CodedUI.md
> -
updated

2024-07-17 12:03 UTC, YuvarajMasilamani commented on wpf/DataGrid/UI-Automation.md
> -
resolved

2024-07-17 12:32 UTC, YuvarajMasilamani commented on wpf/Sparkline/Getting-started.md
>  * Add the following namespace in your XAML page:
i have checked with the concern team they told me to remove the references

2024-07-17 13:11 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [Removing_VS_2012_and_2013](https://ci.syncfusion.com/job/Content/job/wpf-docs/453/console)**

2024-07-17 13:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [Removing_VS_2012_and_2013](https://ci.syncfusion.com/job/Content/job/wpf-docs/453/console)**

2024-07-17 13:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [Removing_VS_2012_and_2013](https://ci.syncfusion.com/job/Content/job/wpf-docs/453/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/453/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/453/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/453/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/453/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/453/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/453/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/453/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/453/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-07-18 10:19 UTC, YuvarajMasilamani commented on wpf/Range-Selector/Getting-Started.md
> -
changed

2024-07-19 11:16 UTC, SubashiniMahendran approved these changes

2024-07-19 11:17 UTC, merged