CurrentUser API UG documentation
syncfusion-content/wpf-docs pull request #1487
Opened 2024-08-28 10:41 UTC by YathavakrishnanMohan

Description :
Add the UG documentation for CurrentUser API

2024-08-28 10:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [905221](https://ci.syncfusion.com/job/Content/job/wpf-docs/507/console)**

2024-08-28 10:44 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/507/artifact/cireports/)<br/>Build Location: [905221](https://ci.syncfusion.com/job/Content/job/wpf-docs/507/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/507/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/507/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/507/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/507/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/507/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/507/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/507/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/507/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-28 11:07 UTC, RajaVigneshB requested changes

2024-08-28 11:07 UTC, RajaVigneshB commented on wpf-toc.html
> +					<li><a href="/wpf/Pdf-Viewer/Changing-the-Current-User">Change the CurrentUser of the annotations</a></li>
Please move the new md file inside the How-To folder

2024-08-28 11:07 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/Changing-the-Current-User.md
> +description: Learn about Change the CurrentUser of annotations in Syncfusion WPF Pdf Viewer control.
Description was not proper. Change it

2024-08-28 11:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [905221](https://ci.syncfusion.com/job/Content/job/wpf-docs/508/console)**

2024-08-28 11:20 UTC, YathavakrishnanMohan commented on wpf-toc.html
> +					<li><a href="/wpf/Pdf-Viewer/Changing-the-Current-User">Change the CurrentUser of the annotations</a></li>
File moved to How-To folder is completed

2024-08-28 11:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [905221](https://ci.syncfusion.com/job/Content/job/wpf-docs/508/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/508/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/508/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/508/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/508/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/508/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/508/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/508/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/508/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-28 11:20 UTC, YathavakrishnanMohan commented on wpf/Pdf-Viewer/Changing-the-Current-User.md
> +description: Learn about Change the CurrentUser of annotations in Syncfusion WPF Pdf Viewer control.
Description is changed properly

2024-08-28 13:45 UTC, Vikassekar requested changes

2024-08-28 13:45 UTC, Vikassekar commented on wpf-toc.html
> +					<li><a href="/wpf/Pdf-Viewer/how-to/Changing-the-Current-User">Change the CurrentUser of the annotations</a></li>
Current User is not only for the annotation so you can "change it as Change the current user in PdfViewer

2024-08-28 13:45 UTC, Vikassekar commented on wpf/Pdf-Viewer/How-To/Changing-the-Current-User.md
> +title: Change the CurrentUser of annotations in Pdf Viewer | Syncfusion
modify the title and describtion.

2024-08-28 13:45 UTC, Vikassekar commented on wpf/Pdf-Viewer/How-To/Changing-the-Current-User.md
> +PdfViewerControl pdfViewer1 = new PdfViewerControl();
Provide proper naming

2024-08-28 13:49 UTC, YathavakrishnanMohan commented on wpf-toc.html
> +					<li><a href="/wpf/Pdf-Viewer/how-to/Changing-the-Current-User">Change the CurrentUser of the annotations</a></li>
Title is changed to  "Change the current user in PdfViewer" completed

2024-08-28 14:05 UTC, YathavakrishnanMohan commented on wpf/Pdf-Viewer/How-To/Changing-the-Current-User.md
> +title: Change the CurrentUser of annotations in Pdf Viewer | Syncfusion
title and description is modified

2024-08-28 14:06 UTC, YathavakrishnanMohan commented on wpf/Pdf-Viewer/How-To/Changing-the-Current-User.md
> +PdfViewerControl pdfViewer1 = new PdfViewerControl();
Naming is changed proper naming

2024-08-28 14:12 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [905221](https://ci.syncfusion.com/job/Content/job/wpf-docs/509/console)**

2024-08-28 14:16 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/wpf-docs/509/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-08-28 14:17 UTC, SyncfusionBuild commented
**CI Status: ABORTED :x:<br/>Source Compilation: Not Started :x:<br/>Build Location: [905221](https://ci.syncfusion.com/job/Content/job/wpf-docs/509/)<br/>**

2024-08-28 14:17 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [905221](https://ci.syncfusion.com/job/Content/job/wpf-docs/510/console)**

2024-08-28 15:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [905221](https://ci.syncfusion.com/job/Content/job/wpf-docs/510/console)**

2024-08-28 15:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [905221](https://ci.syncfusion.com/job/Content/job/wpf-docs/510/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/510/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/510/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/510/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/510/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/510/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/510/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/510/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/510/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-29 11:42 UTC, Vikassekar requested changes

2024-08-29 11:42 UTC, Vikassekar commented on wpf/Pdf-Viewer/How-To/Changing-the-Current-User.md
> +The PDF Viewer allows you to change the CurrentUser. If the CurrentUser property is not set, it defaults to the system user name. When you set the CurrentUser, you will see the changes in the annotat
modify the content as below 
The PDF Viewer allows you to change the CurrentUser. If the CurrentUser property is not set, it defaults to the system user name. When you set the CurrentUser, the changes will be reflected in the author property of newly added annotations. The following code example illustrates how to set the CurrentUser:

2024-08-29 11:50 UTC, YathavakrishnanMohan commented on wpf/Pdf-Viewer/How-To/Changing-the-Current-User.md
> +The PDF Viewer allows you to change the CurrentUser. If the CurrentUser property is not set, it defaults to the system user name. When you set the CurrentUser, you will see the changes in the annotat
Content changing is completed

2024-08-29 12:03 UTC, Vikassekar approved these changes

2024-08-29 12:04 UTC, Vikassekar approved these changes

2024-08-29 12:06 UTC, RajaVigneshB approved these changes

2024-08-29 12:08 UTC, merged