UG documentation on disabling the Undo/redo operation in WPF PDFViewer
syncfusion-content/wpf-docs pull request #1528
Opened 2024-10-23 11:45 UTC by Yaminisrisf4389

Description :
Add the UG documentation for disabling the Undo/redo operation

2024-10-23 11:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [910841_Undo/redo](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/console)**

2024-10-23 12:02 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/artifact/cireports/)<br/>Build Location: [910841_Undo/redo](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [1](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [2](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/571/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-23 12:14 UTC, SyncfusionBuild commented
The running **[CI Job](https://ci.syncfusion.com/job/Content/job/wpf-docs/572/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2024-10-23 12:39 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [910841_Undo/redo](https://ci.syncfusion.com/job/Content/job/wpf-docs/574/console)**

2024-10-24 11:13 UTC, Vikassekar requested changes

2024-10-24 11:13 UTC, Vikassekar commented on wpf-toc.html
> +					<li><a href="/wpf/Pdf-Viewer/how-to/Disable-the-UndoRedo-operation">Disable the UndoRedo Operation in PdfViewer</a></li>
just mention "Disable the Undo Redo operation".

2024-10-24 11:13 UTC, Vikassekar commented on wpf-toc.html
> +					<li><a href="/wpf/Pdf-Viewer/how-to/Disable-the-UndoRedo-operation">Disable the UndoRedo Operation in PdfViewer</a></li>
Provide space for Undo redo

2024-10-24 11:13 UTC, Vikassekar commented on wpf/Pdf-Viewer/How-To/Disable-the-UndoRedo-operation .md
> +description: Learn about how to Disable the UndoRedo Operation in Syncfusion WPF Pdf Viewer control using Limit property of UndoRedoSettings.
Just mention using UndoRedoSettings, no need to mention property name .

2024-10-24 11:13 UTC, Vikassekar commented on wpf/Pdf-Viewer/How-To/Disable-the-UndoRedo-operation .md
> +The PDF Viewer allows you to Disable the UndoRedo Operation. If the Limit property of UndoRedoSettings is not set, it defaults value will be limited to 100.By reducing the value of this property to z
instead of starting the content "pdfviewer allow you" use " To diable Undo Redo operation in  PdfViewer" Also check the content was properly formed in grammar and with cases.

2024-10-24 11:13 UTC, Vikassekar commented on wpf/Pdf-Viewer/How-To/Disable-the-UndoRedo-operation .md
> +pdfViewer.UndoRedoSettings.Limit = 0;
In VB we wont use ";" at end, can you check this code?

2024-10-24 11:13 UTC, Vikassekar commented on wpf/Pdf-Viewer/How-To/Disable-the-UndoRedo-operation .md
> +---
can you remove the space in the file name, and provide gap between undo redo ?

2024-10-24 11:51 UTC, Yaminisrisf4389 commented on wpf-toc.html
> +					<li><a href="/wpf/Pdf-Viewer/how-to/Disable-the-UndoRedo-operation">Disable the UndoRedo Operation in PdfViewer</a></li>
Resolved

2024-10-24 11:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [910841_Undo/redo](https://ci.syncfusion.com/job/Content/job/wpf-docs/583/console)**

2024-10-24 12:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [910841_Undo/redo](https://ci.syncfusion.com/job/Content/job/wpf-docs/583/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/583/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/583/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/583/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/583/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/583/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/583/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/583/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/583/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/583/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-10-24 12:08 UTC, Yaminisrisf4389 commented on wpf-toc.html
> +					<li><a href="/wpf/Pdf-Viewer/how-to/Disable-the-UndoRedo-operation">Disable the UndoRedo Operation in PdfViewer</a></li>
Resolved

2024-10-24 12:08 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Disable-the-UndoRedo-operation .md
> +description: Learn about how to Disable the UndoRedo Operation in Syncfusion WPF Pdf Viewer control using Limit property of UndoRedoSettings.
Resolved

2024-10-24 12:08 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Disable-the-UndoRedo-operation .md
> +The PDF Viewer allows you to Disable the UndoRedo Operation. If the Limit property of UndoRedoSettings is not set, it defaults value will be limited to 100.By reducing the value of this property to z
Resolved

2024-10-24 12:09 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Disable-the-UndoRedo-operation .md
> +pdfViewer.UndoRedoSettings.Limit = 0;
Resolved

2024-10-24 12:09 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Disable-the-UndoRedo-operation .md
> +---
Resolved

2024-10-24 12:43 UTC, Vikassekar approved these changes

2024-10-24 12:44 UTC, merged