559101 - Update the "Working with commands" UG contents
syncfusion-content/wpf-docs pull request #1547
Opened 2024-11-06 10:08 UTC by Dhileep4290

**Description: **
                  Created UG for the working with commands section by adding UG content for the missing commands
                   *  This code change is for the working with commands section in WPF- PdfViewer.
                   *  Added detailed descriptions, examples, and guidelines for the missing commands with code examples.
                   *  Improved clarity and structure of the UG for ease of understanding of the UG.

2024-11-06 10:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-559101-working_with_commands_UG](https://ci.syncfusion.com/job/Content/job/wpf-docs/607/console)**

2024-11-06 10:12 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-559101-working_with_commands_UG](https://ci.syncfusion.com/job/Content/job/wpf-docs/607/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/607/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/607/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/607/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/607/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/607/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/607/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/607/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/607/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/607/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-18 09:57 UTC, RajaVigneshB requested changes

2024-11-18 09:57 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/Working-with-command-binding/Binding-commands-to-a-button.md
> +The list of commands below rotates the specific pages in a PDF document. These commands allow for rotating pages to a custom angle, or by 90 degrees in either a clockwise or counterclockwise directio
Can we able to rotate to custom angle?
Please the below UG for reference: https://help.syncfusion.com/wpf/pdf-viewer/working-with-command-binding/binding-commands-to-a-button#page-navigations

2024-11-18 09:57 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/Working-with-command-binding/Binding-commands-to-a-button.md
> +We can rotate the pages 90 degrees with respect to the current rotation angle in a counterclockwise direction. It is achieved by giving the array of indexes of the page number passed as command param
Change the content for all the sub headings as we discussed

2024-11-18 09:57 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/Working-with-command-binding/Binding-commands-to-a-button.md
> +N>
Remove unwanted notes

2024-11-19 12:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-559101-working_with_commands_UG](https://ci.syncfusion.com/job/Content/job/wpf-docs/626/console)**

2024-11-19 12:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-559101-working_with_commands_UG](https://ci.syncfusion.com/job/Content/job/wpf-docs/626/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/626/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/626/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/626/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/626/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/626/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/626/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/626/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/626/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/626/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-27 12:15 UTC, Vikassekar approved these changes

2024-11-27 12:20 UTC, merged