SEO-191923--wpf-page-with-redirect
syncfusion-content/wpf-docs pull request #1555
Opened 2024-11-12 14:59 UTC by hillary-ochieng

Hi @Yvone-Atieno 

|Title|Description|
|--|--|
|Task Category|Site Audit - Page with redirect|
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Hotfix PR|https://github.com/syncfusion-content/wpf-docs/pull/1555|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/191923|
|Excel/SharePoint link| NA|

|Changes made|Reason for changes|
|--|--|
|Changed redirect link  |  To avoid redirection 301 or 302,providing direct link    |     

Regards,
Hillary

2024-11-12 15:02 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/614/artifact/cireports/)<br/>Build Location: [SEO-191923--wpf-page-with-redirect](https://ci.syncfusion.com/job/Content/job/wpf-docs/614/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/614/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/614/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/614/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/614/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/614/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/614/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/614/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/614/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [2](https://ci.syncfusion.com/job/Content/job/wpf-docs/614/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-13 05:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-191923--wpf-page-with-redirect](https://ci.syncfusion.com/job/Content/job/wpf-docs/615/console)**

2024-11-13 05:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-191923--wpf-page-with-redirect](https://ci.syncfusion.com/job/Content/job/wpf-docs/615/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/615/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/615/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/615/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/615/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/615/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/615/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/615/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/615/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/615/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-15 07:32 UTC, Yvone-Atieno requested changes
Commented

2024-11-15 07:32 UTC, Yvone-Atieno commented on wpf/TreeGrid/Export-To-Excel.md
> +You can export the tree grid to Excel by using the [ExportToExcel](html#Syncfusion_UI_Xaml_TreeGrid_Converter_TreeGridExcelhttps://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.TreeGrid.Converter.Tre
Check the updated link

2024-11-18 12:55 UTC, hillary-ochieng commented on wpf/TreeGrid/Export-To-Excel.md
> +You can export the tree grid to Excel by using the [ExportToExcel](html#Syncfusion_UI_Xaml_TreeGrid_Converter_TreeGridExcelhttps://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.TreeGrid.Converter.Tre
Updated proper link

2024-11-18 14:23 UTC, Yvone-Atieno approved these changes
Approved

2024-11-25 10:29 UTC, merged