871183-Whether need to unload externally, before loading new document
syncfusion-content/wpf-docs pull request #1558
Opened 2024-11-14 06:43 UTC by Yaminisrisf4389

Description :
Add the UG documentation for need to unload externally, before loading new document

2024-11-14 06:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/console)**

2024-11-14 06:47 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/artifact/cireports/)<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [2](https://ci.syncfusion.com/job/Content/job/wpf-docs/616/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-14 06:54 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/617/console)**

2024-11-14 07:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/618/console)**

2024-11-18 05:55 UTC, RajaVigneshB requested changes

2024-11-18 05:55 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +The [Unload](https://help.syncfusion.com/cr/wpf/Syncfusion.Windows.PdfViewer.PdfViewerControl.html#Syncfusion_Windows_PdfViewer_PdfViewerControl_Unload) method of [PdfViewerControl](https://help.sync
The content was not proper. Pelase refer the below UG https://help.syncfusion.com/wpf/pdf-viewer/how-to/change-the-selection-color-of-annotations

2024-11-18 05:55 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +pdfviewer.Unload();
This code snippet was not enough. Add this in a button click

2024-11-18 05:55 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +N>* In PdfViewerControl, there’s no need to manually unload the current document before loading a new one, as the control automatically unloads the previous document after the new one has finished lo
Content need to be modified

2024-11-18 06:44 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +The [Unload](https://help.syncfusion.com/cr/wpf/Syncfusion.Windows.PdfViewer.PdfViewerControl.html#Syncfusion_Windows_PdfViewer_PdfViewerControl_Unload) method of [PdfViewerControl](https://help.sync
Content was modified Kindly review

2024-11-18 06:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/621/console)**

2024-11-18 06:45 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +pdfviewer.Unload();
Button click added feedback addressed

2024-11-18 06:45 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +N>* In PdfViewerControl, there’s no need to manually unload the current document before loading a new one, as the control automatically unloads the previous document after the new one has finished lo
Content was modified kindky review

2024-11-18 06:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/621/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/621/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/621/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/621/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/621/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/621/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/621/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/621/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/621/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/621/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-18 09:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/622/console)**

2024-11-18 09:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/622/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/622/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/622/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/622/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/622/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/622/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/622/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/622/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/622/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/622/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-18 10:30 UTC, RajaVigneshB requested changes

2024-11-18 11:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/623/console)**

2024-11-18 11:51 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +PDF Viewer allows you to unload the document with the  [Unload](https://help.syncfusion.com/cr/wpf/Syncfusion.Windows.PdfViewer.PdfViewerControl.html#Syncfusion_Windows_PdfViewer_PdfViewerControl_Unl
As you said I changed the content

2024-11-18 11:52 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +N>* In PdfViewerControl, it is recommended not to manually unload the document externally.
As you said I modified the note content

2024-11-18 11:53 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/623/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/623/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/623/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/623/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/623/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/623/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/623/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/623/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/623/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/623/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-11-18 12:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/624/console)**

2024-11-18 12:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/624/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/624/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/624/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/624/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/624/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/624/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/624/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/624/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/624/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/624/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2025-01-10 04:50 UTC, RajaVigneshB requested changes

2025-01-10 04:50 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +description: Learn how the Syncfusion WPF PDF Viewer control automatically unloads the current document when loading a new one, eliminating the need for manual unloading.
Add trademark symbols in all the necessary places

2025-01-10 04:50 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +private void button1_Click(object sender, RoutedEventArgs e)
Change the event name as "UnloadButton_Click"

2025-01-10 04:50 UTC, RajaVigneshB commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +PDF Viewer allows you to unload the PDF document with the  [Unload(Boolean)](https://help.syncfusion.com/cr/wpf/Syncfusion.Windows.PdfViewer.PdfViewerControl.html#Syncfusion_Windows_PdfViewer_PdfView
Change the content as per we discussed

2025-01-10 05:28 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/840/console)**

2025-01-10 05:29 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +description: Learn how the Syncfusion WPF PDF Viewer control automatically unloads the current document when loading a new one, eliminating the need for manual unloading.
trademark symbols added

2025-01-10 05:29 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +private void button1_Click(object sender, RoutedEventArgs e)
As you said I changed the event name

2025-01-10 05:30 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/How-To/Unload-the-document.md
> +PDF Viewer allows you to unload the PDF document with the  [Unload(Boolean)](https://help.syncfusion.com/cr/wpf/Syncfusion.Windows.PdfViewer.PdfViewerControl.html#Syncfusion_Windows_PdfViewer_PdfView
As you said I changed the content

2025-01-10 05:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/840/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/840/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/840/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/840/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/840/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/840/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/840/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/840/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/840/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/840/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2025-01-10 09:12 UTC, RajaVigneshB approved these changes

2025-01-10 09:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/844/console)**

2025-01-10 09:19 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [871183](https://ci.syncfusion.com/job/Content/job/wpf-docs/844/)<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/844/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/844/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/844/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/844/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/844/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/844/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/844/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/844/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/844/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2025-01-10 11:06 UTC, merged