922442
syncfusion-content/wpf-docs pull request #1580
Opened 2024-12-02 10:19 UTC by Yaminisrisf4389

2024-12-02 10:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [922442_ContextMenu_UG](https://ci.syncfusion.com/job/Content/job/wpf-docs/643/console)**

2024-12-02 10:29 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [922442_ContextMenu_UG](https://ci.syncfusion.com/job/Content/job/wpf-docs/643/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/643/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/643/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/643/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/643/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/643/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/643/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/643/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/643/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/643/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-02 10:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [922442_ContextMenu_UG](https://ci.syncfusion.com/job/Content/job/wpf-docs/644/console)**

2024-12-02 10:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [922442_ContextMenu_UG](https://ci.syncfusion.com/job/Content/job/wpf-docs/644/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/644/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/644/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/644/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/644/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/644/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/644/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/644/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/644/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>MD Tag Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/wpf-docs/644/artifact/cireports/MDTagsValidation/MDTagsValidation.html)<br/>**

2024-12-05 08:33 UTC, Vikassekar requested changes
As discuss in the call can you please modify the content ?

2024-12-06 02:40 UTC, Vikassekar requested changes

2024-12-06 02:40 UTC, Vikassekar commented on wpf/Pdf-Viewer/Customizing-context-menu.md
> +	    e.MenuItems.Insert(0,(new ContextMenuItem { Content = "Lock Annotation" }));
image add and content are mismatched , can you change the screen shot for add

2024-12-06 04:43 UTC, Yaminisrisf4389 commented on wpf/Pdf-Viewer/Customizing-context-menu.md
> +	    e.MenuItems.Insert(0,(new ContextMenuItem { Content = "Lock Annotation" }));
I changed the screen shot for adding menu item

2024-12-06 06:57 UTC, Vikassekar approved these changes
Approving this

2024-12-06 06:57 UTC, merged