WPF-61114 Prepared UG content for SmithChart
syncfusion-content/wpf-docs pull request #295
Opened 2022-06-15 18:05 UTC by TamilarasanGunasekaran

Hi @vigneshrameshsync ,
                   I have prepared UG content for SmithChart.

2022-06-15 18:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/293/console)**

2022-06-15 19:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/294/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/294/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/294/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/294/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/294/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/294/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/294/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-16 18:33 UTC, vigneshrameshsync requested changes

2022-06-16 18:33 UTC, vigneshrameshsync commented on wpf/Smith-Chart/Series.md
> +## Customizing Series Data
This is just a heading, not an API. So, please avoid unwanted casing.

2022-06-16 18:33 UTC, vigneshrameshsync commented on wpf/Smith-Chart/Series.md
> +The property *ArrangeByIndex* value is indicating whether to render the data based on the provided index order.the data points are rendered based on the provided index when it is true otherwise, the
API should be provided as a link using the syntax \[\`API_NAME\`\](LINK).

You just provided an API summary as a description. It is wrong, the description should explain the use-case of this API clearly. Please refer to the below links.

https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis/arrangeByIndex.html

https://help.syncfusion.com/wpf/classic/chart/chart-axis#indexed-x-values

2022-06-16 18:33 UTC, vigneshrameshsync commented on wpf/Smith-Chart/Series.md
> +   <syncfusion:LineSeries ArrangeByIndex="False">
By the default value is false, then why should we set it explicitly?

2022-06-16 18:33 UTC, vigneshrameshsync commented on wpf/Smith-Chart/Series.md
> +![Customizing Series Data](Series_images/SmithChart_Series_Image.png)
This is an alternate text for an output image which will be displayed when the image is not get loaded. So, please avoid unnecessary case changes.

Please use the below sample data to capture the output screenshot
https://blazor.syncfusion.com/demos/smith-chart/print-and-export?theme=fluent

2022-06-17 10:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/298/console)**

2022-06-17 10:32 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/298/artifact/cireports/)<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/298/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/298/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/298/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/298/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/298/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/298/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/298/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-17 10:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/299/console)**

2022-06-17 12:33 UTC, vigneshrameshsync requested changes

2022-06-17 12:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/300/console)**

2022-06-17 12:48 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/300/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/300/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/300/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/300/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/300/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/300/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/300/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-17 13:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/302/console)**

2022-06-17 13:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/302/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/302/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/302/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/302/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/302/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/302/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/302/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-17 13:29 UTC, TamilarasanGunasekaran commented on wpf/Smith-Chart/Series.md
> +By default, data points will be sorted and plotted based on the resistance value. By setting the [`ArrangeByIndex`]() property value as true, they can be plotted based on it's index value.
I have changed as you mentioned.

2022-06-17 13:30 UTC, TamilarasanGunasekaran commented on wpf/Smith-Chart/Series.md
> +## Customizing Series Data
I have corrected.

2022-06-17 13:30 UTC, TamilarasanGunasekaran commented on wpf/Smith-Chart/Series.md
> +   <syncfusion:LineSeries ArrangeByIndex="False">
I have corrected it.

2022-06-17 14:15 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/303/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/303/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/303/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/303/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/303/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/303/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/303/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-18 06:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/304/console)**

2022-06-18 06:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/304/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/304/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/304/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/304/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/304/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/304/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/304/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-18 06:40 UTC, vigneshrameshsync approved these changes
The content is fine.

2022-06-20 05:22 UTC, Chrispineagunja commented on wpf/Smith-Chart/Series.md
> +By default, the data points are plotted by sorting them based on the resistance values and it can be plotted based on their index value as it is by setting the [`ArrangeByIndex`]() property as true.
By default, the data points are plotted by sorting them based on the resistance values and they can be plotted based on their index value as it is by setting the [`ArrangeByIndex`]() property as true.

2022-06-20 06:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/305/console)**

2022-06-20 06:58 UTC, TamilarasanGunasekaran commented
rebuild

2022-06-20 07:05 UTC, TamilarasanGunasekaran commented on wpf/Smith-Chart/Series.md
> +By default, the data points are plotted by sorting them based on the resistance values and it can be plotted based on their index value as it is by setting the [`ArrangeByIndex`]() property as true.
I have updated.

2022-06-20 07:32 UTC, TamilarasanGunasekaran commented
rebuild

2022-06-20 07:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/306/console)**

2022-06-20 07:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SmithChart-non-linear-data-point-rendering-support](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/306/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/306/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/306/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/306/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/306/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/306/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/306/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-20 08:24 UTC, merged