WPF-61657 Container Header support document is added
syncfusion-content/wpf-docs pull request #384
Opened 2022-09-22 03:43 UTC by KarkuvelRajan

WPF-61657 Container Header support document is added

2022-09-22 03:44 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-61657_Container_Header_Support_Documentation_is_added](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/409/console)**

2022-09-22 03:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-61657_Container_Header_Support_Documentation_is_added](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/409/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/409/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/409/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/409/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/409/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/409/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/409/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-26 09:05 UTC, prakashperumal1892 commented on wpf/Diagram/Container.md
> +## Header support in Container
Setting a Header

2022-09-26 09:25 UTC, prakashperumal1892 requested changes

2022-09-26 09:25 UTC, prakashperumal1892 commented on wpf/Diagram/Container.md
> +* The size of the container header can be controlled by using the `UnitWidth` and `UnitHeight` properties of header.
You can textually describe a container by using its 'Header' property. Also, users can customize the header's appearance using header's "ShapeStyle" property.

The following code example explains how to define a header for the container and alter its appearance.




You can edit the header by double-clicking the region of the container's header or by pressing F2.

2022-09-26 09:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-61657_Container_Header_Support_Documentation_is_added](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/411/console)**

2022-09-26 09:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-61657_Container_Header_Support_Documentation_is_added](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/411/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/411/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/411/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/411/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/411/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/411/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/411/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-26 10:21 UTC, sarathkumarvenkatesan commented on wpf/Diagram/Container.md
> +You can textually describe a container by using its 'Header' property. Also, users can customize the header's appearance using header's "ShapeStyle" property.
Link property to its API link

2022-09-26 10:28 UTC, KarkuvelRajan commented on wpf/Diagram/Container.md
> +You can textually describe a container by using its 'Header' property. Also, users can customize the header's appearance using header's "ShapeStyle" property.
Hi @sarathkumarvenkatesan 

After this Volume release only we will be able to add the API links.

Regards,
Karkuvel Rajan S

2022-09-26 11:31 UTC, OnyimbiNelson commented on wpf/Diagram/Container.md
> +You can textually describe a container by using its 'Header' property. Also, users can customize the header's appearance using header's "ShapeStyle" property.
You can textually describe a container by using its 'Header' property. Also, users can customize the header's appearance using the header's "ShapeStyle" property.

2022-09-26 11:31 UTC, OnyimbiNelson commented on wpf/Diagram/Container.md
> +The following code example explains how to define a container header and its customization.
The following code example explains how to define a container header and its customization:

2022-09-26 11:32 UTC, OnyimbiNelson commented on wpf/Diagram/Container.md
> +N> You can edit the header by double-clicking the region of the container's header or by pressing F2.
N> You can edit the header by double-clicking the region of the container's header, or by pressing F2.

2022-09-26 11:32 UTC, OnyimbiNelson commented on wpf/Diagram/Container.md
>  Container Nodes can be predefined and added to stencil. You can drop those Containers into Diagram, when required.
Container Nodes can be predefined and added to the stencil. You can drop those Containers into Diagram when required.

2022-09-26 16:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-61657_Container_Header_Support_Documentation_is_added](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/413/console)**

2022-09-26 16:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-61657_Container_Header_Support_Documentation_is_added](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/413/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/413/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/413/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/413/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/413/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/413/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/wpf-docs/413/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-09-27 07:34 UTC, sarathkumarvenkatesan approved these changes

2022-09-27 07:34 UTC, sarathkumarvenkatesan approved these changes

2022-09-27 07:38 UTC, prakashperumal1892 approved these changes
Approved

2022-09-27 07:39 UTC, merged