SEO-3380 - WPF Control
syncfusion-content/wpf-docs pull request #572
Opened 2023-03-06 15:02 UTC by Sharly-Atieno

Hi @Aishwarya-Ganesan,
Added redirect link for WPF Controls.

Regards,
Sharly A.

2023-03-06 15:03 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-3380-WPF-Controls](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/527/console)**

2023-03-06 15:04 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3380-WPF-Controls](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/527/console)**

2023-03-06 15:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3380-WPF-Controls](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/527/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/527/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/527/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/527/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/527/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/527/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/527/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-07 06:43 UTC, gowthamanthavasiyappan requested changes

2023-03-07 06:43 UTC, gowthamanthavasiyappan commented on wpf/DataGrid/Export-To-PDF.md
> +You can refer [PDF documentation](https://help.syncfusion.com/#saving-a-pdf-document-to-file-system).
Use this link - https://help.syncfusion.com/file-formats/pdf/open-and-save-pdf-file-in-c-sharp-vb-net#saving-a-pdf-document-to-file-system

2023-03-07 06:43 UTC, gowthamanthavasiyappan commented on wpf/DataGrid/Export-To-PDF.md
> +You can refer [PDF documentation](https://help.syncfusion.com/#saving-a-pdf-document-to-stream).
Use this link - https://help.syncfusion.com/file-formats/pdf/open-and-save-pdf-file-in-c-sharp-vb-net#saving-a-pdf-document-to-stream

2023-03-07 06:43 UTC, gowthamanthavasiyappan commented
Commented

2023-03-07 08:26 UTC, Sharly-Atieno commented on wpf/DataGrid/Export-To-PDF.md
> +You can refer [PDF documentation](https://help.syncfusion.com/#saving-a-pdf-document-to-stream).
Redirect link added

2023-03-07 08:26 UTC, Sharly-Atieno commented on wpf/DataGrid/Export-To-PDF.md
> +You can refer [PDF documentation](https://help.syncfusion.com/#saving-a-pdf-document-to-file-system).
Redirect link added

2023-03-07 08:26 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3380-WPF-Controls](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/529/console)**

2023-03-07 08:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3380-WPF-Controls](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/529/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/529/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/529/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/529/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/529/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/529/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/529/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2023-03-21 08:44 UTC, gowthamanthavasiyappan approved these changes
Approved

2023-03-23 06:34 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-03-23 06:35 UTC, merged