SEO-3554 - WPF Controls
syncfusion-content/wpf-docs pull request #629
Opened 2023-04-04 12:58 UTC by Sharly-Atieno

Hi @Aishwarya-Ganesan,
Please review the changes for blazor controls.

Regards,
Sharly A.

2023-04-04 12:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3554-WPF-controls](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/603/console)**

2023-04-05 05:53 UTC, gowthamanthavasiyappan requested changes
Commented

2023-04-05 05:53 UTC, gowthamanthavasiyappan commented on wpf/Maps/Getting-Started.md
> +![Adding SfMap reference from NuGet](Getting-Started_images/Adding-SfMaps-reference.png)
Update proper image name, you need to change the image name in the source location also.

2023-04-05 06:10 UTC, Sharly-Atieno commented on wpf/Maps/Getting-Started.md
> +![Adding SfMap reference from NuGet](Getting-Started_images/Adding-SfMaps-reference.png)
modified

2023-04-05 06:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3554-WPF-controls](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/606/console)**

2023-04-05 06:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3554-WPF-controls](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/606/)<br/>**

2023-04-05 06:27 UTC, gowthamanthavasiyappan approved these changes
Approved

2023-07-07 09:07 UTC, Girija-Rajendran approved these changes

2023-07-07 09:15 UTC, merged