SEO-3550 WPF changes
syncfusion-content/wpf-docs pull request #632
Opened 2023-04-05 13:47 UTC by Scholar-jaruha

Hi @gowthamanthavasiyappan,
Please find changes made.
Regards,
Scholar.

2023-04-05 13:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3550-WPF-changes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/608/console)**

2023-04-05 13:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-3550-WPF-changes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/608/)<br/>**

2023-04-11 04:18 UTC, gowthamanthavasiyappan requested changes
Commented

2023-04-11 04:18 UTC, gowthamanthavasiyappan commented on wpf/DataGrid/Master-Details-View.md
> +You can get the sample from [here](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.DetailsViewDataGrid.html).
Why you have updated help link instead of FT link?

2023-04-11 11:41 UTC, Scholar-jaruha commented on wpf/DataGrid/Master-Details-View.md
> +You can get the sample from [here](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.DetailsViewDataGrid.html).
changed

2023-04-11 11:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-3550-WPF-changes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/613/console)**

2023-04-14 11:19 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-04-14 11:20 UTC, merged