SEO-171754
syncfusion-content/wpf-docs pull request #654
Opened 2023-05-03 14:20 UTC by Edithabich

Hi @Aishwarya-Ganesan ,

Have made the changes in redirect links. Please review.

Thanks.
Regards,
Edith.

2023-05-03 14:21 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171754](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/635/console)**

2023-05-04 06:04 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-171754](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/636/console)**

2023-05-04 06:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171754](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/636/console)**

2023-05-04 06:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171754](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/636/)<br/>**

2023-05-04 15:30 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171754](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/642/console)**

2023-05-04 15:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171754](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/642/)<br/>**

2023-05-05 04:59 UTC, gowthamanthavasiyappan requested changes
Commented

2023-05-05 04:59 UTC, gowthamanthavasiyappan commented on wpf/DataGrid/Column-Types.md
> +You can change the renderer of existing column by removing the predefined cell type value from [CellRenderers](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html#Syncfusion_UI
Can you check and confirm this redirection link with the product team?

2023-05-05 04:59 UTC, gowthamanthavasiyappan commented on wpf/DataGrid/Column-Types.md
> +You can create a new column by deriving [GridColumn](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.GridColumn.html), rendered in UI using customized [CellType](https://help.syncfusion.co
Recheck this link also.

2023-05-05 04:59 UTC, gowthamanthavasiyappan commented on wpf/DataGrid/Grouping.md
> +You can cancel the group is being collapsed by using [GroupChangingEventArgs.Cancel](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html#Syncfusion_UI_Xaml_Grid_SfDataGrid_Show
Redirection link is wrong, update proper link here.

2023-05-05 12:49 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171754](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/644/)<br/>**

2023-05-08 11:18 UTC, Edithabich commented on wpf/DataGrid/Column-Types.md
> +You can create a new column by deriving [GridColumn](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.GridColumn.html), rendered in UI using customized [CellType](https://help.syncfusion.co
I have changed the redirect link here

2023-05-08 11:33 UTC, Edithabich commented on wpf/DataGrid/Grouping.md
> +You can cancel the group is being collapsed by using [GroupChangingEventArgs.Cancel](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html#Syncfusion_UI_Xaml_Grid_SfDataGrid_Show
Have changed the proper link here

2023-05-08 11:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171754](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/647/console)**

2023-05-08 11:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171754](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/647/)<br/>**

2023-05-17 04:48 UTC, merged