SEO-171911-WPF Control missing h1
syncfusion-content/wpf-docs pull request #664
Opened 2023-05-11 13:57 UTC by Sharly-Atieno

Hi @Aishwarya-Ganesan,
Please review the changes for missing H1 below.

Regards,
Sharly A.

2023-05-11 13:58 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-171911-WPF-Control](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/655/console)**

2023-05-11 14:07 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-171911-WPF-Control](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/656/console)**

2023-05-11 14:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171911-WPF-Control](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/656/console)**

2023-05-11 14:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171911-WPF-Control](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/656/)<br/>**

2023-05-12 04:38 UTC, gowthamanthavasiyappan requested changes
Commented

2023-05-12 04:38 UTC, gowthamanthavasiyappan commented on wpf/Release-notes/Migratingtov16.1.0.24.md
> +# Volume 1 Migration document in WPF RichTextBox(SfRichTextBoxAdv)
Check control name properly.

2023-05-12 05:22 UTC, Sharly-Atieno commented on wpf/Release-notes/Migratingtov16.1.0.24.md
> +# Volume 1 Migration document in WPF RichTextBox(SfRichTextBoxAdv)
done

2023-05-12 05:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171911-WPF-Control](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/657/console)**

2023-05-12 05:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171911-WPF-Control](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/657/)<br/>**

2023-05-15 05:16 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171911-WPF-Control](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/658/console)**

2023-05-15 05:16 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171911-WPF-Control](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/658/)<br/>**

2023-05-16 09:29 UTC, gowthamanthavasiyappan approved these changes
Approved

2023-05-17 07:17 UTC, Girija-Rajendran commented on wpf/Release-notes/Migratingtov16.1.0.24.md
> +# Volume 1 Migration document in WPF Release Notes
Please check title, description, and H1

2023-07-06 06:33 UTC, closed without merging