SEO-172844-WPF-weblink-validatetor-image
syncfusion-content/wpf-docs pull request #693
Opened 2023-06-16 08:55 UTC by Edithabich

Hi @MallikaRK ,
Please review the changes made in image name alt text and image folder.
Thanks.
Regards,
Edith.

2023-06-16 08:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172844-WPF-weblink-validatetor-images](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/705/console)**

2023-06-16 08:58 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172844-WPF-weblink-validatetor-images](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/705/)<br/>**

2023-06-20 06:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172844-WPF-weblink-validatetor-images](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/743/console)**

2023-06-20 06:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172844-WPF-weblink-validatetor-images](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/743/)<br/>**

2023-06-21 10:06 UTC, MallikaRK requested changes
Commented

2023-06-23 15:39 UTC, Edithabich commented on wpf/Diagram/Getting-Started.md
> +![WPF Diagram from Designer](getting-started_images\wpf-diagram-designer.png)
Resolved

2023-06-23 15:40 UTC, Edithabich commented on wpf/Diagram/Getting-Started.md
> +![WPF Diagram Interact with Stencil](getting-started_images\wpf-diagram-interact-stencil.gif)
resolved

2023-06-23 15:42 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172844-WPF-weblink-validatetor-images](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/776/console)**

2023-06-23 15:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172844-WPF-weblink-validatetor-images](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/776/)<br/>**

2023-06-27 08:49 UTC, MallikaRK approved these changes
Approved

2023-07-19 12:03 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-07-19 12:03 UTC, merged