SEO-173276-WPF-Image-Changes
syncfusion-content/wpf-docs pull request #694
Opened 2023-06-16 09:45 UTC by Scholar-jaruha

Hi @MallikaRK,
Please find changes made under image section.
Regards,
Scholar.

2023-06-16 09:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173276-WPF-Image-Changes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/706/console)**

2023-06-16 09:47 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173276-WPF-Image-Changes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/706/)<br/>**

2023-06-21 06:28 UTC, MallikaRK requested changes
Commented

2023-06-21 06:28 UTC, MallikaRK commented on wpf/Radial-Gauge/Header.md
why you mentioned two control names here. 
circular gauge/radial gauge.
Use any one of the control name. Check and update in all places.

2023-06-21 06:28 UTC, MallikaRK commented on wpf/Radial-Gauge/Header.md
> +![CircularGauge header with custom position in WPF Radial Gauge](header_images/wpf-radial-gaugecircular-gauge-header-custon-position.png)
recheck image name.

2023-06-21 06:28 UTC, MallikaRK commented on wpf/Radial-Gauge/Header.md
> +![CircularGauge Header with customization in WPF Radial Gauge](header_images/wpf-radial-gauge-circular-gauge-header-customization.png)
Use any one of the control name. 
Check and update in all places.

2023-06-23 07:17 UTC, Scholar-jaruha commented on wpf/Radial-Gauge/Getting-Started.md
> +![Adding gauge reference from NuGet in WPF Radial Gauge](getting-started_images/wpf-radial-gauge-adding-gauge-reference.png)
Image name changed

2023-06-23 07:19 UTC, Scholar-jaruha commented on wpf/Radial-Gauge/Header.md
Changed

2023-06-23 07:20 UTC, Scholar-jaruha commented on wpf/Radial-Gauge/Header.md
> +![CircularGauge header with custom position in WPF Radial Gauge](header_images/wpf-radial-gaugecircular-gauge-header-custon-position.png)
changes made

2023-06-23 07:20 UTC, Scholar-jaruha commented on wpf/Radial-Gauge/Header.md
> +![CircularGauge Header with customization in WPF Radial Gauge](header_images/wpf-radial-gauge-circular-gauge-header-customization.png)
updated

2023-06-23 09:23 UTC, MallikaRK approved these changes
Approved

2023-06-26 10:23 UTC, Aishwarya-Ganesan commented
Rebuild

2023-06-27 07:16 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-06-27 07:16 UTC, merged