SEO-173296 WPF Chart Technical Indicators
syncfusion-content/wpf-docs pull request #703
Opened 2023-06-16 12:59 UTC by Yvone-Atieno

Hi @MallikaRK ,

Have renamed image folder, changed and image alt.

Regards,
Yvone.

2023-06-16 13:00 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173296-WPF-Charts-Technical-Indicators](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/715/console)**

2023-06-16 13:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173296-WPF-Charts-Technical-Indicators](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/715/)<br/>**

2023-06-21 07:41 UTC, MallikaRK requested changes
Commented

2023-06-21 07:41 UTC, MallikaRK commented on wpf/Charts/Technical-Indicators.md
> +![Accumulation distribution indicator in WPF Chart](Technical-Indicators_images/wpf-chart-accumulation-indicator.png)
Image FOLDER Name still in Capital. recheck

2023-06-21 08:34 UTC, Yvone-Atieno commented on wpf/Charts/Technical-Indicators.md
> +![Accumulation distribution indicator in WPF Chart](Technical-Indicators_images/wpf-chart-accumulation-indicator.png)
rechecked

2023-06-21 08:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173296-WPF-Charts-Technical-Indicators](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/754/console)**

2023-06-21 08:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173296-WPF-Charts-Technical-Indicators](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/754/)<br/>**

2023-06-21 09:48 UTC, MallikaRK requested changes
Commented

2023-06-21 09:48 UTC, MallikaRK commented on wpf/Charts/Technical-Indicators.md
> +![Accumulation distribution indicator in WPF Chart](technical-Indicators_images/wpf-chart-accumulation-indicator.png)
Still captital case exists in Image Folder Name. Check and correct it.

2023-06-21 12:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173296-WPF-Charts-Technical-Indicators](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/755/console)**

2023-06-21 12:49 UTC, MallikaRK approved these changes
Approved

2023-06-22 11:35 UTC, Girija-Rajendran commented on wpf/Charts/Technical-Indicators.md
> +![Accumulation distribution indicator in WPF Chart](technical-indicators_images/wpf-chart-accumulation-indicator.png)
Changed this name in folder

2023-06-27 06:58 UTC, Yvone-Atieno commented on wpf/Charts/Technical-Indicators.md
> +![Accumulation distribution indicator in WPF Chart](technical-indicators_images/wpf-chart-accumulation-indicator.png)
the folder is changed

2023-06-27 12:42 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-06-27 12:42 UTC, merged