SEO-173296 WPF Chart SeriesTypes
syncfusion-content/wpf-docs pull request #705
Opened 2023-06-16 13:16 UTC by Yvone-Atieno

Hi @MallikaRK ,

Have renamed image folder, changed and image alt.

Regards,
Yvone.

2023-06-16 13:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173296-WPF-Chart-SeriesTypes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/717/console)**

2023-06-16 13:18 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173296-WPF-Chart-SeriesTypes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/717/)<br/>**

2023-06-21 07:38 UTC, MallikaRK requested changes
Commented

2023-06-21 07:38 UTC, MallikaRK commented on wpf/Charts/SeriesTypes/Financial.md
> +![Comparing high value of WPF Candle Chart](series_images/wpf-candle-chart-compare-high-value.png)
You have changed the image name here. But you missed to edit the image name in series_images folder. Recheck again.

2023-06-21 08:32 UTC, Yvone-Atieno commented on wpf/Charts/SeriesTypes/Financial.md
> +![Comparing high value of WPF Candle Chart](series_images/wpf-candle-chart-compare-high-value.png)
renamed

2023-06-21 08:33 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173296-WPF-Chart-SeriesTypes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/753/console)**

2023-06-21 08:34 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173296-WPF-Chart-SeriesTypes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/753/)<br/>**

2023-06-21 09:47 UTC, MallikaRK approved these changes
Approved

2023-06-22 11:33 UTC, Girija-Rajendran approved these changes

2023-06-22 11:34 UTC, merged