SEO-173276-WPF-Image-Link-Changes
syncfusion-content/wpf-docs pull request #718
Opened 2023-06-19 08:39 UTC by Scholar-jaruha

Hi @MallikaRK,
Please find changes made under image section.
Regards,
Scholar.

2023-06-19 08:41 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173276-WPF-Image-Link-Changes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/729/)<br/>**

2023-06-21 07:25 UTC, MallikaRK requested changes
Commented

2023-06-21 07:25 UTC, MallikaRK commented on wpf/Sunburst-Chart/Getting-Started.md
> +![WPF Sunburst Chart Project Solution reference](getting-started_images/wpf-sunburst-chart-project-solution.png)
Image alt text name casing is not proper. Should add Caps letter in starting of the text, control name, platform name, other text should be in small casing. So, change it.

2023-06-23 07:33 UTC, Scholar-jaruha commented on wpf/RichTextBox/Getting-Started.md
> +![WPF RichTextBox Application](getting-started_images/wpf-richtextbox-application.jpeg)
I have reverted the changes

2023-06-23 07:46 UTC, Scholar-jaruha commented on wpf/Sunburst-Chart/Getting-Started.md
> +![WPF Sunburst Chart Project Solution reference](getting-started_images/wpf-sunburst-chart-project-solution.png)
changed

2023-06-23 07:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173276-WPF-Image-Link-Changes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/761/console)**

2023-06-23 08:02 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173276-WPF-Image-Link-Changes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/761/)<br/>**

2023-06-23 09:37 UTC, MallikaRK requested changes
Commented

2023-06-23 09:37 UTC, MallikaRK commented on wpf/Scheduler/Overview.md
> +![WPF scheduler rirstdayofweek](overview_images/wpf-scheduler-firstdayofweek.png)
Spelling mistake in alt text.
control name should be casing.
image name should be proper, give hyphen.

2023-06-23 09:37 UTC, MallikaRK commented on wpf/Tab-Splitter/Overview.md
> +![Overview in WPF TabSplitter](overview_images/wpf-tab-splitter-overview.png)
overview of is suitable. Revert your changes in Alt text.

2023-06-23 13:50 UTC, Scholar-jaruha commented on wpf/Scheduler/Overview.md
> +![WPF scheduler rirstdayofweek](overview_images/wpf-scheduler-firstdayofweek.png)
spelling error corrected

2023-06-26 08:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173276-WPF-Image-Link-Changes](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/779/)<br/>**

2023-06-26 10:11 UTC, MallikaRK approved these changes
Approved

2023-06-26 12:12 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-06-26 12:13 UTC, merged