SEO-173276-WPF-Images-Redirection
syncfusion-content/wpf-docs pull request #725
Opened 2023-06-19 12:01 UTC by Scholar-jaruha

Hi @MallikaRK,
Please find changes made under image section.
Regards,
Scholar.

2023-06-19 12:03 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-173276-WPF-Images-Redirection](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/738/console)**

2023-06-19 12:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173276-WPF-Images-Redirection](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/738/console)**

2023-06-19 12:08 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173276-WPF-Images-Redirection](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/738/)<br/>**

2023-06-21 07:29 UTC, MallikaRK requested changes
Commented

2023-06-21 07:29 UTC, MallikaRK commented on wpf/Themes/Skin-Manager.md
> +![Customizing theme while run time in Light](skin-manager_images/wpf-themes-switching-theme-at-runtime-light.png)
change the image name as
wpf-skin-manager-light-theme

2023-06-21 07:29 UTC, MallikaRK commented on wpf/Themes/Skin-Manager.md
> +![Customizing theme while run time in Dark](skin-manager_images/wpf-themes-switching-theme-at-runtime-Dark.png)
Change the name as per previous comment

2023-06-23 08:10 UTC, Scholar-jaruha commented on wpf/Themes/Skin-Manager.md
> +![Customizing theme while run time in Light](skin-manager_images/wpf-themes-switching-theme-at-runtime-light.png)
changed

2023-06-23 08:10 UTC, Scholar-jaruha commented on wpf/Themes/Skin-Manager.md
> +![Customizing theme while run time in Dark](skin-manager_images/wpf-themes-switching-theme-at-runtime-Dark.png)
changed

2023-06-23 08:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173276-WPF-Images-Redirection](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/762/console)**

2023-06-23 08:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173276-WPF-Images-Redirection](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/762/)<br/>**

2023-06-23 09:43 UTC, MallikaRK requested changes
Commented

2023-06-23 09:43 UTC, MallikaRK commented on wpf/Tabbed-MDI-Form/Getting-Started.md
> -![Minimizing MDI window in Document Container](Minimizing-MDI-window_images/Minimizing-MDI-window_img1.jpeg)
Why you removed the image here?

2023-06-23 09:43 UTC, MallikaRK commented on wpf/Themes/Skin-Manager.md
> +![Add SfSkinManager Reference](skin-manager_images/wpf-theme-reference.png)
Add platform name here. 
Add WPF SkinManager Reference - use this word in alt text. 
Check and update in all places.

2023-06-23 09:43 UTC, MallikaRK commented on wpf/Themes/Theme-Studio.md
> +![WPF Theme Studio Palette](themestudio_images/wpf-themestudio-palette.gif)
give hyphen in image name [all places]
theme-studio

2023-06-23 14:02 UTC, Scholar-jaruha commented on wpf/Tabbed-MDI-Form/Getting-Started.md
> -![Minimizing MDI window in Document Container](Minimizing-MDI-window_images/Minimizing-MDI-window_img1.jpeg)
I have reverted

2023-06-26 08:28 UTC, Scholar-jaruha commented on wpf/Themes/Skin-Manager.md
> +![Add SfSkinManager Reference](skin-manager_images/wpf-theme-reference.png)
changed

2023-06-26 08:36 UTC, Scholar-jaruha commented on wpf/Themes/Theme-Studio.md
> +![WPF Theme Studio Palette](themestudio_images/wpf-themestudio-palette.gif)
Added hyphen

2023-06-26 08:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173276-WPF-Images-Redirection](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/778/console)**

2023-06-26 08:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173276-WPF-Images-Redirection](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/778/)<br/>**

2023-06-26 10:13 UTC, MallikaRK approved these changes
Approved

2023-06-26 12:25 UTC, Aishwarya-Ganesan approved these changes
Changes are fine

2023-06-26 12:25 UTC, merged