SEO-173280-Image-Alt-TextBox-WPF
syncfusion-content/wpf-docs pull request #728
Opened 2023-06-20 07:23 UTC by berylouma

Hello,

I have worked on the links with redirects and changing image names and alt text.

Regards,
Beryl.

2023-06-20 07:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173280-Image-Alt-TextBox-WPF](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/745/console)**

2023-06-21 09:02 UTC, MallikaRK requested changes
Commented

2023-06-21 09:02 UTC, MallikaRK commented on wpf/PropertyGrid/Getting-Started.md
> +![ Populating the SelectedEmployee object properties into the PropertyGrid control](getting-started_images/wpf-propertygrid-populating-properties)
image file format name is missing. Please update properly.
.png is missing here.

2023-06-23 08:31 UTC, berylouma commented on wpf/PropertyGrid/Getting-Started.md
> +![ Populating the SelectedEmployee object properties into the PropertyGrid control](getting-started_images/wpf-propertygrid-populating-properties)
Updated image name properly

2023-06-23 08:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-173280-Image-Alt-TextBox-WPF](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/763/console)**

2023-06-23 08:33 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-173280-Image-Alt-TextBox-WPF](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/763/)<br/>**

2023-07-26 10:04 UTC, Girija-Rajendran approved these changes

2023-07-26 10:07 UTC, MallikaRK approved these changes
Approved

2023-07-26 10:11 UTC, merged