WPF-834981-Annotation Nudging UG
syncfusion-content/wpf-docs pull request #737
Opened 2023-06-22 09:37 UTC by ArunKumarSF4054

**Description**
**Added Documentation for new feature :** 
Add necessary information and gif file  about Annotation Nudging in the UG .

2023-06-22 09:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-834981-Annotation_nudging_UG](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/757/console)**

2023-06-22 09:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-834981-Annotation_nudging_UG](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/757/)<br/>**

2023-06-22 12:48 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-834981-Annotation_nudging_UG](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/759/console)**

2023-06-22 12:50 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-834981-Annotation_nudging_UG](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/759/)<br/>**

2023-06-23 05:19 UTC, KarkuvelRajan requested changes
**Please do these below changes:**

Click the annotation ---> Select the annotation

In order to enable the nudging feature for annotations in an annotation editor, ---> In order to enable the nudging feature for annotations

you can allow the annotation to be moved by a single pixel. ---> you can be able to nudge the annotation by one pixel in specific direction based on the arrow key press.

Based on the key press the annotation will move towards the particular direction. ---> remove this line

Diagram allows you to specify the amount of nudging around the annotation. ---> Diagram allows you to specify the nudging area for the annotation.

nudge the annotation behind of this drag limit value. ---> nudge the annotation behind the provided drag limit value.

Default value is (10, 10, 10, 10). ---> Default value of 'Draglimit' is (10, 10, 10, 10).

2023-06-26 09:00 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-834981-Annotation_nudging_UG](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/780/)<br/>**

2023-06-26 09:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-834981-Annotation_nudging_UG](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/781/)<br/>**

2023-06-27 06:22 UTC, prakashperumal1892 approved these changes
Approved

2023-06-27 06:23 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WPF-834981-Annotation_nudging_UG](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/783/console)**

2023-06-27 06:23 UTC, KarkuvelRajan approved these changes
Approved

2023-06-27 06:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WPF-834981-Annotation_nudging_UG](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/783/)<br/>**

2023-06-27 06:41 UTC, merged