SEO-174775 WPF Page with Redirect-
syncfusion-content/wpf-docs pull request #802
Opened 2023-08-03 08:16 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan,

Have changed WPF Page with Redirect, please review.

Regards,
Yvone.

2023-08-03 08:17 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174775-WPF-Page-with-Redirect-](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/859/console)**

2023-08-03 08:20 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174775-WPF-Page-with-Redirect-](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/859/)<br/>**

2023-08-08 09:32 UTC, MallikaRK requested changes
Commented

2023-08-08 09:32 UTC, MallikaRK commented on wpf/DataGrid/Grouping.md
> +https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.canceleventargs.cancel?view=net-5.0
Seems you mistakenly placed the URL. Update the URL in needed place.

2023-08-08 12:42 UTC, Yvone-Atieno commented on wpf/DataGrid/Grouping.md
> +https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.canceleventargs.cancel?view=net-5.0
updated

2023-08-11 11:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174775-WPF-Page-with-Redirect-](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/871/console)**

2023-08-11 11:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-174775-WPF-Page-with-Redirect-](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/871/)<br/>**

2023-08-11 12:24 UTC, MallikaRK approved these changes
Approved

2023-08-14 13:45 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-08-14 13:45 UTC, merged