2023-Vol3 UG content for Show annotations, Modified date and Clear all annotations.
syncfusion-content/wpf-docs pull request #833
Opened 2023-08-23 14:17 UTC by KrithikaGanesan

UG content for Show annotations, Modified date and Clear all annotations.

2023-09-05 07:33 UTC, Vikassekar requested changes
Also ensure all the content grammar and content modification using Chat GPT.

2023-09-05 07:33 UTC, Vikassekar commented on wpf/Pdf-Viewer/Organize-Pages.md
> +## Show the annotations in page organizer
Instead of using page organizer use page organizer panel.  Also it seems we exposed about showing annotation instead mention Show/Hide

2023-09-05 07:33 UTC, Vikassekar commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer allows the user to delete all annotations programmatically without user interaction.
add the below line 
This option helps users to remove unwanted annotations from the document.

2023-09-05 07:33 UTC, Vikassekar commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer allows the user to delete all annotations programmatically using the ClearAllAnnotations method.
for mentioning the API use api help link
ClearAllAnnotations

2023-09-05 07:33 UTC, Vikassekar commented on wpf/Pdf-Viewer/Organize-Pages.md
> +You can show the annotations in page organizer of the ‘PdfViewerControl’ by setting the ‘PageOrganizerSettings.ShowAnnotations’ property to true.
missed to mention form field and mention the API use api help link

2023-09-05 07:33 UTC, Vikassekar commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer also allows the user to delete all annotations from a specific page programmatically using the overload ClearAllAnnotations method with a specified page number on which the annotations are
for mentioning the API use api help link

2023-09-05 07:33 UTC, Vikassekar commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +{% highlight C# %}
missed VB code add it.

2023-09-05 07:33 UTC, Vikassekar commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +//delete all annotations
missed VB code add it

2023-09-05 07:33 UTC, Vikassekar commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +## Set the modified date of an annotation
Update the annotation's modified date. 
Change the topic as above

2023-09-05 07:33 UTC, Vikassekar commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer allows the user to set the modified date of an annotation programmatically without user interaction.
add points about its use case

2023-09-05 07:33 UTC, Vikassekar commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +### How to set the modified date of an annotation?
change the sub topic similar to the topic. 
we need to mention about default setting and annotation change event setting.
also add Vb code for below code snippet.

2023-09-05 10:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [2023-Vol3](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/888/console)**

2023-09-05 10:55 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Organize-Pages.md
> +## Show the annotations in page organizer
Yes. I have used page organizer panel. Yes I have mentioned as Show/Hide

2023-09-05 10:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [2023-Vol3](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/888/)<br/>**

2023-09-05 11:01 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer allows the user to delete all annotations programmatically without user interaction.
Yes. I have added the below line

2023-09-05 11:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [2023-Vol3](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/889/console)**

2023-09-05 11:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [2023-Vol3](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/889/)<br/>**

2023-09-05 11:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [2023-Vol3](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/890/console)**

2023-09-05 11:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [2023-Vol3](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/890/)<br/>**

2023-09-05 11:13 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer allows the user to delete all annotations programmatically using the ClearAllAnnotations method.
Yes. I have added API link.

2023-09-05 11:14 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Organize-Pages.md
> +You can show the annotations in page organizer of the ‘PdfViewerControl’ by setting the ‘PageOrganizerSettings.ShowAnnotations’ property to true.
Yes. I have mentioned form field and added API link.

2023-09-05 11:14 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [2023-Vol3](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/891/)<br/>**

2023-09-05 11:15 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +{% highlight C# %}
Yes. I have added the VB code

2023-09-05 11:17 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Organize-Pages.md
> +You can show the annotations in page organizer of the ‘PdfViewerControl’ by setting the ‘PageOrganizerSettings.ShowAnnotations’ property to true.
Yes. I have added API link.

2023-09-05 11:17 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer also allows the user to delete all annotations from a specific page programmatically using the overload ClearAllAnnotations method with a specified page number on which the annotations are
Yes. I have added API link.

2023-09-05 11:18 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +## Set the modified date of an annotation
I have changed the topic as above

2023-09-05 11:19 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +### How to set the modified date of an annotation?
I have changed the topic similar to sub topic
I have mentioned about default annotation setting and annotation change event setting.
I have also added VB code for below code snippet

2023-09-13 11:47 UTC, Vikassekar requested changes

2023-09-13 11:47 UTC, Vikassekar commented on wpf/Pdf-Viewer/Organize-Pages.md
> +You can show or hide the annotations and form fields in the page organizer panel of the ‘PdfViewerControl’ by setting the [PageOrganizerSettings.ShowAnnotations](https://help.syncfusion.com/cr/wpf/Sy
Instead of mentioning true, we need to mention, true or false.

2023-09-13 11:47 UTC, Vikassekar commented on wpf/Pdf-Viewer/Organize-Pages.md
> +Refer to the following code example to show the annotations in page organizer panel.
annotations and form fields

2023-09-13 11:47 UTC, Vikassekar commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer also allows the user to delete all annotations from a specific page programmatically using the overload [ClearAllAnnotations](https://help.syncfusion.com/cr/wpf/Syncfusion.Windows.PdfViewe
Instead  The page number should be passed as a parameter that needs to be deleted. 
Use 
 The page number which we pass as a parameter, its annotations get deleted.

2023-09-13 11:47 UTC, Vikassekar commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer allows the user to update the [ModifiedDate](https://help.syncfusion.com/cr/wpf/Syncfusion.Windows.PdfViewer.AnnotationSettings.html#Syncfusion_Windows_PdfViewer_AnnotationSettings_Modifie
Instead 
With this feature, users can specify the date and time according to their preferences.
use 
With this feature, users can alter the modified date and time according to their preferences.

2023-09-13 11:47 UTC, Vikassekar commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +N> Similarly, we can implement it for all other annotations.
Instead of note use it in above code snippet.

2023-09-13 12:11 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer allows the user to set the modified date of an annotation programmatically without user interaction.
I have added use case

2023-09-13 12:12 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Organize-Pages.md
> +You can show or hide the annotations and form fields in the page organizer panel of the ‘PdfViewerControl’ by setting the [PageOrganizerSettings.ShowAnnotations](https://help.syncfusion.com/cr/wpf/Sy
Yes I have modified

2023-09-13 12:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [2023-Vol3](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/915/console)**

2023-09-13 12:12 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Organize-Pages.md
> +Refer to the following code example to show the annotations in page organizer panel.
Yes I have modified

2023-09-13 12:12 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer also allows the user to delete all annotations from a specific page programmatically using the overload [ClearAllAnnotations](https://help.syncfusion.com/cr/wpf/Syncfusion.Windows.PdfViewe
Yes I have modified as mentioned

2023-09-13 12:12 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +PDF Viewer allows the user to update the [ModifiedDate](https://help.syncfusion.com/cr/wpf/Syncfusion.Windows.PdfViewer.AnnotationSettings.html#Syncfusion_Windows_PdfViewer_AnnotationSettings_Modifie
Yes I have modified as mentioned

2023-09-13 12:12 UTC, KrithikaGanesan commented on wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
> +N> Similarly, we can implement it for all other annotations.
Yes I have modified as mentioned

2023-09-13 12:13 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [2023-Vol3](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/915/)<br/>**

2023-09-13 12:30 UTC, Vikassekar requested changes

2023-09-13 12:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [2023-Vol3](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/916/console)**

2023-09-13 12:36 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [2023-Vol3](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/916/)<br/>**

2023-09-13 13:11 UTC, Vikassekar approved these changes

2023-09-13 13:12 UTC, merged