Update Change-the-position-of-the-Chart-Legend.md
syncfusion-content/wpf-docs pull request #839
Opened 2023-08-30 13:52 UTC by berylouma

Hello,

I have worked on the missing H1.

Regards,
Beryl.

2023-08-30 13:53 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-174767-WPF-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/885/console)**

2023-08-30 13:56 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-174767-WPF-Missing-H1](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/885/console)**

2023-09-04 08:47 UTC, Yvone-Atieno requested changes
Commented

2023-09-04 08:47 UTC, Yvone-Atieno commented on wpf/Classic/Chart/How-to/Change-the-position-of-the-Chart-Legend.md
> +# Change the position of the Chart Legend
H1 must contain platform name, include platform name

2023-09-05 08:14 UTC, berylouma commented on wpf/Classic/Chart/How-to/Change-the-position-of-the-Chart-Legend.md
> +# Change the position of the Chart Legend
Updated

2023-09-05 08:58 UTC, Yvone-Atieno approved these changes
Approved

2023-09-20 13:38 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-09-20 13:38 UTC, merged