SEO-175653-WPF-Links-With-Redirects
syncfusion-content/wpf-docs pull request #844
Opened 2023-09-07 07:58 UTC by berylouma

Hello,

Worked on the links with redirects.

Regards,
Beryl.

2023-09-07 08:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175653-WPF-Links-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/893/console)**

2023-09-07 08:12 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175653-WPF-Links-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/893/)<br/>**

2023-09-12 09:51 UTC, berylouma commented on wpf/DataGrid/UI-Automation.md
>  To test SfDataGrid with CUITs, build the Extension Project and place it in the mentioned location. You can get the Extension Project of SfDataGrid from [this](http://www.syncfusion.com/downloads/supp
Updated

2023-09-12 09:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175653-WPF-Links-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/912/console)**

2023-09-12 09:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175653-WPF-Links-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/912/)<br/>**

2023-09-12 14:49 UTC, Yvone-Atieno requested changes
Commented

2023-09-12 14:49 UTC, Yvone-Atieno commented on wpf/DataGrid/Merge-Cells.md
>  You can trigger [SfDataGrid.QueryCoveredRange](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html) event for particular cell by removing its range from [SfDataGrid.CoveredCell
Cr link not changed
<img width="761" alt="image" src="https://github.com/syncfusion-content/wpf-docs/assets/95272306/989227d7-e624-4c8a-8658-9520970f25b0">

2023-09-13 13:05 UTC, berylouma commented on wpf/DataGrid/Merge-Cells.md
>  You can trigger [SfDataGrid.QueryCoveredRange](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html) event for particular cell by removing its range from [SfDataGrid.CoveredCell
Changed

2023-09-13 13:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175653-WPF-Links-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/918/console)**

2023-09-13 13:07 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175653-WPF-Links-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/918/)<br/>**

2023-09-14 05:23 UTC, Yvone-Atieno approved these changes
Approved

2023-09-29 07:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175653-WPF-Links-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/962/console)**

2023-09-29 07:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175653-WPF-Links-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/962/)<br/>**

2023-11-10 09:26 UTC, Aishwarya-Ganesan approved these changes
Fine.

2023-11-10 09:26 UTC, merged