SEO-175653-WPF-Pages-With-Redirects
syncfusion-content/wpf-docs pull request #845
Opened 2023-09-07 09:02 UTC by berylouma

Hello,

Worked on the links with redirects.

Regards,
Beryl.

2023-09-07 09:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175653-WPF-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/894/console)**

2023-09-07 09:05 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175653-WPF-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/894/)<br/>**

2023-09-08 09:15 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175653-WPF-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/899/console)**

2023-09-08 09:17 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175653-WPF-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/899/)<br/>**

2023-09-11 12:59 UTC, Yvone-Atieno requested changes
Commented

2023-09-11 12:59 UTC, Yvone-Atieno commented on wpf/Integer-TextBox/Appearance.md
> +The [IntegerTextBox](https://www.syncfusion.com/wpf-ui-controls/integer-textbox) control [Foreground](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.control.foreground?view=netf
Update the correct link

2023-09-12 09:50 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175653-WPF-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/911/console)**

2023-09-12 09:50 UTC, berylouma commented on wpf/Integer-TextBox/Appearance.md
> +The [IntegerTextBox](https://www.syncfusion.com/wpf-ui-controls/integer-textbox) control [Foreground](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.control.foreground?view=netf
Updated

2023-09-12 09:56 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175653-WPF-Pages-With-Redirects](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/911/)<br/>**

2023-09-12 14:54 UTC, Yvone-Atieno approved these changes
Approved

2023-11-10 09:27 UTC, Aishwarya-Ganesan approved these changes
Fine.

2023-11-10 09:27 UTC, merged