SEO-175680-WPF-UG-page-with-redirects-links
syncfusion-content/wpf-docs pull request #852
Opened 2023-09-13 12:37 UTC by Edithabich

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.

Regards,
Edith.

2023-09-13 12:38 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/917/console)**

2023-09-13 12:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/917/console)**

2023-09-13 12:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/917/)<br/>**

2023-09-21 12:28 UTC, Yvone-Atieno requested changes
Commented

2023-09-21 12:28 UTC, Yvone-Atieno commented on wpf/DataGrid/Column-Types.md
>  You can allow end-user to navigate the `Uri` when the cell value contains valid `Uri` address or using [CurrentCellRequestNavigate](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGr
Update the correct cr link

2023-09-21 12:28 UTC, Yvone-Atieno commented on wpf/DataGrid/Editing.md
>  [CurrentCellBeginEdit](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html) event occurs when the [CurrentCell](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.GridC
Update correct cr link
<img width="593" alt="image" src="https://github.com/syncfusion-content/wpf-docs/assets/95272306/3ad37e5e-8da4-4226-9174-2ac9c5345c66">

2023-09-21 12:28 UTC, Yvone-Atieno commented on wpf/Multi-Column-DropDown/Popup-customization.md
> +[PopupClosing](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl.html) event is fired when the popup is closing. You can use this event to skip the popup closing
Check all cr links and update the correct links

2023-09-21 12:28 UTC, Yvone-Atieno commented on wpf/Multi-Column-DropDown/Popup-customization.md
> +[PopupClosed](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl.html) event is fired when the popup is closed. [PopupClosedEventArgs](https://help.syncfusion.com
Change cr link

2023-09-21 12:28 UTC, Yvone-Atieno commented on wpf/Multi-Column-DropDown/Popup-customization.md
> +[PopupOpening](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl.html) event is fired when the popup is opening. You can use this event to skip the popup opening
Update correct cr links

2023-09-22 08:33 UTC, Edithabich commented on wpf/DataGrid/Editing.md
>  [CurrentCellBeginEdit](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html) event occurs when the [CurrentCell](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.GridC
Resolved

2023-09-22 08:42 UTC, Edithabich commented on wpf/Multi-Column-DropDown/Popup-customization.md
> +[PopupClosing](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl.html) event is fired when the popup is closing. You can use this event to skip the popup closing
rechecked and updated proper links

2023-09-22 08:43 UTC, Edithabich commented on wpf/Multi-Column-DropDown/Popup-customization.md
> +[PopupClosed](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl.html) event is fired when the popup is closed. [PopupClosedEventArgs](https://help.syncfusion.com
resolved

2023-09-22 08:43 UTC, Edithabich commented on wpf/Multi-Column-DropDown/Popup-customization.md
> +[PopupOpening](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfMultiColumnDropDownControl.html) event is fired when the popup is opening. You can use this event to skip the popup opening
updated

2023-09-22 08:46 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/948/console)**

2023-09-22 08:48 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/948/)<br/>**

2023-09-27 09:56 UTC, Yvone-Atieno commented on wpf/DataGrid/Column-Types.md
> +SfDataGrid triggers, [CurrentCellDropDownSelectionChanged](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html) event, when the SelectedValue is changed.[CurrentCellDropDownSel
Check this link
<img width="625" alt="image" src="https://github.com/syncfusion-content/wpf-docs/assets/95272306/f4b2a12c-faf3-42c4-8a11-9468dee803e5">

2023-09-28 06:07 UTC, Edithabich commented on wpf/DataGrid/Column-Types.md
> +SfDataGrid triggers, [CurrentCellDropDownSelectionChanged](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html) event, when the SelectedValue is changed.[CurrentCellDropDownSel
resolved

2023-09-28 06:07 UTC, Edithabich commented on wpf/DataGrid/Column-Types.md
> +SfDataGrid triggers, [CurrentCellDropDownSelectionChanged](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html) event, when the SelectedValue is changed.[CurrentCellDropDownSel
resolved

2023-09-28 06:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/957/console)**

2023-09-28 06:24 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/957/)<br/>**

2023-09-28 07:39 UTC, Yvone-Atieno requested changes
Commented

2023-09-28 07:39 UTC, Yvone-Atieno commented on wpf/DataGrid/Column-Types.md
> +You can change the renderer of existing column by removing the predefined cell type value from [CellRenderers](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html#Syncfusion_UI
Check the last link

2023-09-28 07:39 UTC, Yvone-Atieno commented on wpf/DataGrid/Column-Types.md
> +* [IsThreeState](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.GridCheckBoxColumn.html) - By default, the `GridCheckBoxColumn` has `Checked` and `Unchecked` state. You can enable another
Check this link

2023-09-28 09:45 UTC, Edithabich commented on wpf/DataGrid/Column-Types.md
> +* [IsThreeState](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.GridCheckBoxColumn.html) - By default, the `GridCheckBoxColumn` has `Checked` and `Unchecked` state. You can enable another
updated

2023-09-28 09:45 UTC, Edithabich commented on wpf/DataGrid/Column-Types.md
> +You can change the renderer of existing column by removing the predefined cell type value from [CellRenderers](https://help.syncfusion.com/cr/wpf/Syncfusion.UI.Xaml.Grid.SfDataGrid.html#Syncfusion_UI
updated

2023-09-28 09:47 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/959/console)**

2023-09-28 09:53 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/959/console)**

2023-09-28 10:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/959/)<br/>**

2023-10-18 14:24 UTC, Aishwarya-Ganesan approved these changes
Fine.

2023-10-18 14:24 UTC, Aishwarya-Ganesan approved these changes
Fine.

2023-10-18 14:35 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/983/console)**

2023-10-18 14:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/983/)<br/>**

2023-10-18 14:40 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/984/console)**

2023-10-18 14:44 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-175680-WPF-UG-page-with-redirects-links](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/984/)<br/>**

2023-10-31 13:15 UTC, merged