SEO-176130 WPF Redirect
syncfusion-content/wpf-docs pull request #882
Opened 2023-09-22 11:51 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan,

Have changed page with redirect links.

Regards,
Yvone.

2023-09-22 11:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176130-WPF-Redirect](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/950/console)**

2023-09-27 15:26 UTC, MallikaRK requested changes

2023-09-27 15:26 UTC, MallikaRK commented on wpf/Diagram/Interaction/Selection.md
> +* [How to disable the selection in Diagram?](https://support.syncfusion.com/kb/article/5495/how-to-disable-the-selection-in-wpf-diagram?isInternalRefresh=False)
Recheck the KB links.
<img width="980" alt="image" src="https://github.com/syncfusion-content/wpf-docs/assets/44014283/f9449cec-09f0-40a7-a258-b418aefdc8d3">
Check in all places too.

2023-09-29 07:40 UTC, Yvone-Atieno commented on wpf/Diagram/Interaction/Selection.md
> +* [How to disable the selection in Diagram?](https://support.syncfusion.com/kb/article/5495/how-to-disable-the-selection-in-wpf-diagram?isInternalRefresh=False)
checked all links

2023-09-29 07:51 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-176130-WPF-Redirect](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/961/console)**

2023-09-29 07:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-176130-WPF-Redirect](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/961/)<br/>**

2023-10-18 12:58 UTC, MallikaRK approved these changes

2023-10-18 13:18 UTC, merged