ES-851567 Modify TOC File
syncfusion-content/wpf-docs pull request #898
Opened 2023-10-06 10:55 UTC by Venkateshmuruganandam

Hi All,
Modify the TOC file for DocIo and Presentation Product.

Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/851567
Regards
venkatesh

2023-10-06 10:56 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-851567-Modify-Toc-File](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/966/console)**

2023-10-06 10:59 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-851567-Modify-Toc-File](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/966/console)**

2023-10-06 11:01 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-851567-Modify-Toc-File](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/966/)<br/>**

2023-10-06 11:07 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-851567-Modify-Toc-File](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/967/console)**

2023-10-06 11:07 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/967/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-10-06 11:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-851567-Modify-Toc-File](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/968/console)**

2023-10-06 11:09 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-851567-Modify-Toc-File](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/968/)<br/>**

2023-10-06 13:56 UTC, MohanaselvamJothi requested changes

2023-10-06 13:56 UTC, MohanaselvamJothi commented on wpf-toc.html
> +        Word Library (DocIO)
Adding library name is enough. No need to add sub links. Refer PDF

2023-10-09 06:25 UTC, Venkateshmuruganandam commented on wpf-toc.html
> +        Word Library (DocIO)
modofied

2023-10-09 06:26 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [ES-851567-Modify-Toc-File](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/969/console)**

2023-10-09 06:34 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [ES-851567-Modify-Toc-File](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/969/console)**

2023-10-09 06:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [ES-851567-Modify-Toc-File](https://jenkins.syncfusion.com/job/Content/job/wpf-docs/969/)<br/>**

2023-10-10 13:29 UTC, MohanaselvamJothi approved these changes

2023-10-10 13:29 UTC, MohanaselvamJothi commented
Approved the changes.

2023-10-10 13:29 UTC, merged